### ISSUE TITLE
3.7.0 debian packages: wazuh-agent breaks wazuh-manager, wazuh-api

### ISSUE THREAD

**Issue by jhowe-uw** [wazuh/wazuh-packages#102]
Debian 9.6

dselect, add wazuh-agent after installing wazuh-manager, wazuh-api

Expected:

wazuh-agent installs normally ( worked up through 3.6.x )

Actual:

wazuh-manager, wazuh-api get dselected with warning:

wazuh-agent breaks wazuh-manager
wazuh-agent conflicts with wazuh-api

Thanks

**Comment by alberpilot** [comment]
Hello @jhowe-uw 

  The Wazuh Manager is also an agent, the expected behavior is exactly the same as the agent with the difference that Wazuh Manager reports itself (and Wazuh Manager coordinates all agents report). That's why we don't need to install the Wazuh Agent in the same machine as a Manager. 

Please let me know if you have further questions. 

Best regards,

**Comment by alberpilot** [comment]
I proceed to close this issue, please feel free to re-open it again if you have any problem. 
Best regards, 

Alberto R.
