### ISSUE TITLE
RPM spec restart and enable behaviour makes the package impossible to manage

### ISSUE THREAD

**Issue by rossengeorgiev** [wazuh/wazuh-packages#12]
1. `wazuh-manager` enables itself on install

https://github.com/wazuh/wazuh-packages/blob/13c8220cbd1bad6b709aad0bb8216447fc96ea79/rpms/specs/wazuh-manager-2.1.1.spec#L312

This is undesirable behavior. Additionally, this will enable the service after package upgrade/downgrade even when it was disabled previously.

2. `wazuh-manager` will be started upon install/upgrade/downgrade. The only check performed is that the rules are valid.

https://github.com/wazuh/wazuh-packages/blob/13c8220cbd1bad6b709aad0bb8216447fc96ea79/rpms/specs/wazuh-manager-2.1.1.spec#L331-L337

For example, in a production environment one would stop the service, upgrade the package, apply configuration changes, update rules, and then start it. Currently that is impossible as the service will be started after the package install. The obvious workaround is to introduce a temporary file with invalid syntax so the logtest check fails.

`wazuh-agent` has the same issues

**Comment by rossengeorgiev** [comment]
Hello Wazuh, this issue still exists today. Any plans addressing it ?

**Comment by alberpilot** [comment]
Hello @rossengeorgiev 

  Sorry for the very late response. Yes, we are planning to address a solution to this. We will update soon. 

Best regards, 
Alberto R

**Comment by rossengeorgiev** [comment]
It's been a while since I opened this issue. I would love to this be resolved. Fedora/RHEL/CentOS have very clear guidelines around packaging. The specifically cover the issue described originally.

Fedora:
https://docs.fedoraproject.org/en-US/packaging-guidelines/DefaultServices/#_enabling_services_by_default

scriptlets for systemd services: https://docs.fedoraproject.org/en-US/packaging-guidelines/Scriptlets/#_systemd

EPEL packaging guidelines:
https://fedoraproject.org/wiki/EPEL:SysVInitScripts?rd=Packaging:SysVInitScript#Why_don.27t_we....

> Why don't we....
> 
>  ## run 'chkconfig <service> on'?
> 
> If a service should be enabled by default, make this the default in the init script. Doing otherwise will cause the service to be turned on on upgrades if the user explicitly disabled it.
> 
> Note that the default for most network-listening scripts is off. This is done for better security. We have multiple tools that can enable services, including GUIs.
> 
> ## start the service after installation?
> 
> Installations can be in changeroots, in an installer context, or in other situations where you don't want the services started. 

On Fedora/RHEL/CentOS, sysadmins need to be in control of when service start/stop, or are enabled/disabled. That also plays well into automation, and any scripting, around deploying software and changes to production systems.

**Comment by BraulioV** [comment]
Hi @rossengeorgiev,

Sorry for the late response and thank you for your concern. Making this change now is a bit complicated but we are working on it. Let me explain.

As you know, the current situation of  Wazuh's services is not the best one, it may complicate the deployment and its automation, but for lessexperienced users it makes easier the installation since they don't need to worry about enabling or starting the services after upgrading the packages. 

We are pushing hard to make easier to install and use any Wazuh component. For example, in Wazuh 3.9.x we added a [deployment variables](https://documentation.wazuh.com/3.12/installation-guide/installing-wazuh-agent/deployment_variables/linux/deployment_variables_yum.html) to our Linux, macOS and Windows installers to automatically set up the agent and start it by just using environmental variables. For example: 
```shellsession
# WAZUH_MANAGER="10.0.0.2" WAZUH_REGISTRATION_PASSWORD="TopSecret" \
     WAZUH_AGENT_NAME="yum-agent" yum install wazuh-agent
```

This automatically installs, sets up the `ossec.conf` and starts the agent while installing it. Everything is done in a single line.

Later, we worked in these features:
- [Enable the automatic agent deployment in upgrades](https://github.com/wazuh/wazuh-packages/issues/238): this one allows the user to reconfigure the agent using the same variables used in the install process.
- [Include new variable for auto-start the package](https://github.com/wazuh/wazuh-packages/issues/198): this may be more interesting since it is directly related to this issue. This issue adds a new variable to the deployment process to decide if the services must be enabled or not.

The development of both issues is currently stopped since we are planning to do some changes that will affect the deployment process. For example, https://github.com/wazuh/wazuh/issues/4833 will simplify the registration process of the agents.

We have other issues related to the Wazuh's services, like improving the removal of the services in .deb packages, fix installation path of unit files, etc. and we're planning to rework how the packages handles the services and fix the related issues, but we probably will release this with Wazuh 4.x (it is under development but there's no ETA yet), since it requires deep changes in the logic of the .deb and .rpm packages.

I'll keep you updated with any news related to this issue.

Thank you for patience,

Braulio.

**Comment by rossengeorgiev** [comment]
Hi @BraulioV, thanks for the info. I wanted to shine a light on how wazuh fits in an enterprise environment. I very much appreciate all the work you guys do. My comment in the other issues highlight how other software does, I can almost call it the standard way for agents. It makes deployment easy, and at the same time empowers sysadmins. I very much encourage to consider that approach. This a part of the software that changes rarely, and usually takes an effort to get right. Thanks again

**Comment by BraulioV** [comment]
Hi @rossengeorgiev,

We've been working on some changes for the next major release of Wazuh that will fix this issue, alongside more issues related to the wazuh binary packages. These changes have been mainly introduced in #466. 

Referring to the services, we have changed the restart and enable behaviour to this one:
- Now, the services won't be started either enabled in a fresh install or upgrade.
- Now, the upgrade process will keep the services running if they will previously running. Otherwise, they will remain stopped. This was introduced in #481 and #482, and will be improved in #480 by using `systemctl try-restart service_name`.

Any feedback is highly appreciated.

Thanks again,
Braulio.

**Comment by rossengeorgiev** [comment]
Hi @BraulioV, this sound great. I just want to make some comments on the rpm spec. I've just had a scan through the file in master.

I noticed there are no conditions based on OS version, it only check if systemd bin exist to decide whether to use them. Then there some file touching to keep state during upgrade. Location for unit files is also hardcoded. These are problematic.

Here are my suggestions:

* Use systemd macros, which do all the work for you: https://docs.fedoraproject.org/en-US/packaging-guidelines/Scriptlets/#_systemd 
  * unit file install: https://github.com/saltstack/salt/blob/c798380a16afdc44467c6b4a67cf15a6225bca71/pkg/rpm/salt.spec#L213-L225
  * post/postun example: https://github.com/saltstack/salt/blob/c798380a16afdc44467c6b4a67cf15a6225bca71/pkg/rpm/salt.spec#L320-L436

* Make use of `_unitdir` variable: https://docs.fedoraproject.org/en-US/packaging-guidelines/Systemd/#_packaging
  * Example: https://github.com/saltstack/salt/blob/c798380a16afdc44467c6b4a67cf15a6225bca71/pkg/rpm/salt.spec#L97-L117
