### ISSUE TITLE
Include Configuration Assessment policies into Wazuh packages

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh-packages#123]
Hi @wazuh/cicd team,

The development of a new module in charge of performing configuration assessment scans in Wazuh since v3.9.0 is currently located at branch [3.9-sql-rootcheck](https://github.com/wazuh/wazuh/tree/3.9-sql-rootcheck). It includes new policy files classified in OS.

Here you can find the folder tree for those policies: https://github.com/wazuh/wazuh/tree/3.9-sql-rootcheck/etc/configuration_assessment

For 3.9 packages, we should include corresponding policies to the installation folder at the path `$INSTALL_DIR/ruleset/configuration_assessment`.

- Windows msi -> `windows` folder
- Deb package -> `debian` and `generic` folders
- RPM package -> `rhel` and `generic` folders
- CentOS 5 package -> `rhel/5` and `generic` folders
- Suse package -> `suse` and `generic` folders
- Others -> `generic` folder

**Update:**

- The manager package should contain every policy file, in the same directory.

**Update:**

- These two policy files should not be included in the packages: `rhel/cis_rhel_linux_rcl.yml` and `windows/cis_win2012r2_memberL2_rcl.yml`.

**Update:**

- The directory where the policies will be alocated will change from `ruleset/configuration_assessment` to `ruleset/configuration-assessment`.

Regards.

**Comment by okynos** [comment]
Hi @wazuh/core team,

We have added configuration assessment files on RPM and DEB SPEC files, more information about this topic can be viewed on the branch `3.9-sql-rootcheck` of this repository and most detailed on the following commits:
* https://github.com/wazuh/wazuh-packages/commit/b5555abcca6ad524ea365f72dd5d01e944aa2f37, RPM
* https://github.com/wazuh/wazuh-packages/commit/fb8f3b3019e30dedea1da99e184a9b711cf67999, RPM
* https://github.com/wazuh/wazuh-packages/commit/c463d14f843c82244b8fed2de436f3d84258e057, RPM SPECs
* https://github.com/wazuh/wazuh-packages/commit/77e84b9d606e4b16e65563e7705154fdd7ddb713, Debian SPECs

Regards.

**Comment by okynos** [comment]
Hi @wazuh/core team,

We did last changes on configuration assessment files, described below:
* https://github.com/wazuh/wazuh-packages/commit/93c9dcc1e08246a8170a9ed6d037bd34762e8522, Added Debian SPEC changes, now agents don't have application cis by default.
* https://github.com/wazuh/wazuh-packages/commit/30c4ff623341d8cc4f7ee43569906d7e06a7cfd5, Same changes on RPM SPECs.
* https://github.com/wazuh/wazuh-packages/commit/dc398339c889be043d1db941d7b64939e94c53a1, Fixing typo of folder.
* https://github.com/wazuh/wazuh-packages/commit/f6e29cdb910b142d60ab20c5ce307c6343849f59, generic cis of rhel is no longer required.

Regards.

**Comment by okynos** [comment]
Hi @wazuh/core team,

We did last changes on configuration assessment files, described below:
* https://github.com/wazuh/wazuh-packages/commit/4ec36bdff6da9928c5f380a5a54f422d839c6e5a, On this commit we solved the `configuration-assessment` folder name because it changed on Wazuh branch `3.9-sql-rootcheck`.
* Also we have tested RPM and Debian packages and maybe we need to remove some unnecessary files that now also copy install.sh, need a bit of research.

Regards.

**Comment by okynos** [comment]
Hi @wazuh/core team,

We did the last change on configuration assessment files, described below:
* https://github.com/wazuh/wazuh-packages/commit/5292b38a0d61cfa0efc18d6ec3f04e0547353252, due to install.sh that now do the copy of necessary files we have removed the install from SPECs of manager and agent on Debian and, from Manager on RPM.

Regards.
