### ISSUE TITLE
Unattended installer configurations tar file must contain a folder

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-packages#1300]
The unattended installer configuration tar produced file actually have all files without any folder. If a user extracts the tar file, there is not a folder containing all files, but all files scattered over the current user folder. In order to avoid this, the tar file must contain a folder that contains all the necessary files.

**Comment by c-bordon** [comment]
I'm running into some problems in the unattended tests, both in aio and distributed, in the case of aio it only fails for centos 7 and not for ubuntu, and in the case of distributed it fails to find the config.yml, I'm still investigating why this error occurs, I guess it may be because of the tar subfolder, but I did the test changing this: 

https://github.com/wazuh/wazuh-packages/blob/1130b7fdf54251e6af2df693000b5c9689c5e681/unattended_installer/install_functions/installVariables.sh#L19

to 
config_file="${base_path}/wazuh-install-files/config.yml"

and all the tests failed:

```
16:28:13  TASK [Install unattended installer] ********************************************
16:28:13  fatal: [Test_unattended_B464_20220314192415]: FAILED! => {
16:28:13      "changed": true,
16:28:13      "cmd": [
16:28:13          "bash",
16:28:13          "wazuh-install.sh",
16:28:13          "-a",
16:28:13          "-v",
16:28:13          "--disable-spinner"
16:28:13      ],
16:28:13      "delta": "0:00:01.776145",
16:28:13      "end": "2022-03-14 19:28:13.148308",
16:28:13      "rc": 1,
16:28:13      "start": "2022-03-14 19:28:11.372163"
16:28:13  }
16:28:13  
16:28:13  STDOUT:
16:28:13  
16:28:13  14/03/2022 19:28:11 INFO: Starting Wazuh installation assistant. Wazuh version: 4.3.0
16:28:13  14/03/2022 19:28:13 INFO: --- Configuration files ---
16:28:13  14/03/2022 19:28:13 INFO: Generating configuration files.
16:28:13  wazuh-install.sh: line 1336: /tmp/unattended/unattended_installer/wazuh-install-files/config.yml: No such file or directory
16:28:13  14/03/2022 19:28:13 ERROR: No configuration file found. /tmp/unattended/unattended_installer/wazuh-install-files/config.yml.
```

https://devel.ci.wazuh.info/view/Tests/job/Test_unattended/464/console
https://devel.ci.wazuh.info/view/Tests/job/Test_unattended/463/


Actual tests:

Centos 7: https://devel.ci.wazuh.info/view/Tests/job/Test_unattended/466/console
Ubuntu Bionic: https://devel.ci.wazuh.info/view/Tests/job/Test_unattended/465/console

Distributed: https://devel.ci.wazuh.info/view/Tests/job/Test_unattended_distributed/353/console

**Comment by c-bordon** [comment]
PR Merged
