### ISSUE TITLE
SCA files not found when reinstalling

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-packages#137]
CentOS 7, agent 3.9.0

1. `yum install wazuh-agent`
2. `yum reinstall wazuh-agent`
```
...
Running transaction
  Installing : wazuh-agent-3.9.0-1.x86_64                                                                                                     1/1 
cat: /var/ossec/tmp/sca-3.9.0-1-tmp/centos/7/sca.files: No existe el fichero o el directorio
...
```

Now you can repeat step 2, it always throws `cat: /var/ossec/tmp/sca-3.9.0-1-tmp/centos/7/sca.files: No existe el fichero o el directorio`

Regards

**Comment by BraulioV** [comment]
Hi @jesusgn90,

this error appears because the files in `/var/ossec/tmp/sca-3.9.0-1-tmp/` are marked as `%config(missingok)` files. The files marked with this tag shouldn't be installed in the FS because they are used as temporary files, so once they are removed, `rpm` won't installed them again. 

That's the reason why they are not installed during a `reinstall` and this block fails: https://github.com/wazuh/wazuh-packages/blob/9741837d4fc126888b409d42890a5f31b25eb4d1/rpms/SPECS/3.9.0/wazuh-agent-3.9.0.spec#L297-L299

A possible solution to this error is to execute this block of code only and only if the temporary directory exists. 
```shell
if [ -d %{_localstatedir}/ossec/tmp/sca-%{version}-%{release}-tmp/ ]; then
    for sca_file in $(cat %{_localstatedir}/ossec/tmp/sca-%{version}-%{release}-tmp/${CONF_ASSESMENT_DIR}/sca.files); do
    mv %{_localstatedir}/ossec/tmp/sca-%{version}-%{release}-tmp/${sca_file} %{_localstatedir}/ossec/ruleset/sca
    done
fi
```
This will install the files always if you upgrade or downgrade the package and won't fail if you reinstall the package, but the files in `/var/ossec/etc/ruleset/sca` won't be reinstalled.

Another different solution is to remove the `%config(missingok)` files, install the "temporary" files in a new different path, copy the necessary files to the `sca` directory and **don't** remove the "temporary" files. This will fix the upgrade, downgrade and reinstall but the sca files will be duplicated.

We are discussing the best solution to this issue.

Regards.
