### ISSUE TITLE
Unattended detects wazuh-indexer as installed even though it was not installed correctly

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-packages#1374]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.3.0 | Unattended | Install | centos7 |

Testing the unattended with packages from the trash repository, I have observed that the installation of the wazuh-indexer package is not successful, when looking at the log using -v and set -x, I have observed that although the installation fails, the package is marked as installed and fails later when trying to connect with curl

repository used

Repository used:

```
[wazuh]
gpgcheck=1
gpgkey=https://packages-dev.wazuh.com/key/GPG-KEY-WAZUH
enabled=1
name=EL-${releasever} - Wazuh
baseurl=https://packages-dev.wazuh.com/trash/yum/
protect=1
```

Log:

```
Installing:
 wazuh-indexer          x86_64          4.3.0-1            wazuh          361 M

Transaction Summary
================================================================================
Install  1 Package

Total download size: 361 M
Installed size: 614 M
Downloading packages:
https://packages-dev.wazuh.com/trash/yum/wazuh-indexer-4.3.0-1.x86_64.rpm: [Errno 14] HTTPS Error 416 - Requested Range Not Satisfiable
Trying other mirror.


Error downloading packages:
  wazuh-indexer-4.3.0-1.x86_64: [Errno 256] No more mirrors to try.

+ '[' 0 '!=' 0 ']'
+ indexerinstalled=1
+ common_logger 'Wazuh indexer installation finished.'
```

Full log: [unattended.log](https://github.com/wazuh/wazuh-packages/files/8327656/unattended.log)

It is necessary to review this behavior in the other packages

Regards, Raúl

**Comment by c-bordon** [comment]
The error is due to this validation:

```
    if [  "$?" != 0  ]; then
        common_logger -e "Wazuh indexer installation failed."
        installCommon_rollBack
        exit 1
    else
        indexerinstalled="1"
        common_logger "Wazuh indexer installation finished."
    fi
```
When the -v is used in the command, a tee command is added to the yum command and since this command has an exit equal to 0, the validation is not given and enters through the else

```
+ eval 'yum install wazuh-indexer-4.3.0-1 -y 2>&1 | tee -a /var/log/wazuh-install.log'
++ yum install wazuh-indexer-4.3.0-1 -y
++ tee -a /var/log/wazuh-install.log
```

I was testing with this: https://stackoverflow.com/questions/24734850/how-to-get-the-exit-status-of-the-first-command-in-a-pipe
But this doesn't work because when using eval this remains as a single exit

![Screenshot_20220323_154937](https://user-images.githubusercontent.com/64099752/159785470-5a1a3926-9a46-4f26-babd-456e2fb7f925.png)



I keep trying alternatives although at the moment I do not reach a solution
