### ISSUE TITLE
Check if the specified IP exist linked to any network interface using installation assistant

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-packages#1627]
In order to avoid users' mistakes using public IPs, we need to add a check in the Wazuh installation assistant, verifying that the specified IP exists linked to a network interface. 

Note: the certificates of the nodes of the Wazuh installation can be generated by using `--generate-config-files` or `-g` options **in other machines that will not be part of the Wazuh installation**. Because of this, the unattended installer can not check if the IP address of the Wazuh component belongs to the current system in its network interface.
A proposed approach to avoid specifying public IPs is to check if the introduced IP addresses in the `config.yml` are public or private by checking the range of the addresses.

**Comment by davidcr01** [comment]
# Update Report

The necessary changes have to be implemented when the unattended installer reads the `config.yml` file. This is done in two different moments:
- When using the `-g` option to generate the certificates of the nodes.
- When performing an AIO installation.

```
# Creation certificate case: Only AIO and -g option can create certificates.
    if [ -n "${configurations}" ] || [ -n "${AIO}" ]; then
        common_logger "--- Configuration files ---"
        installCommon_createInstallFiles
    fi

    if [ -z "${configurations}" ] && [ -z "${download}" ]; then
        installCommon_extractConfig
        config_file="/tmp/wazuh-install-files/config.yml"
        cert_readConfig
    fi
```
Because of this, the changes will be added to the `cert_readConfig` function.
