### ISSUE TITLE
OVA creation fails with 3.9.1 and 7.1.0

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-packages#176]
Hello team

 The OVA creation script fails with the latest wazuh version due to a not contemplated new architecture done in Elastic 7 (no logstash, no java, etc.). Let's fix this script. 

Best regards, 
Alberto R

**Comment by DFolchA** [comment]
Hello team, 

We have found that there is a good amount of reusable code in the provision scripts of the ova generation so we have decided to create two libraries that will be called by the provision script, elastic_functions.sh will have all the functions related to installing the elastic stack and wazuh_functions that will have all the functions related to installing the agent and the manager. This way we can reduce the complexity of the scripts and make them easier to understand and modify.

I am currently implementing these libraries and modifying the provision script.

Regards,
Daniel Folch.

**Comment by DFolchA** [comment]
Hello team, 

I have finished creating the libraries, and tomorrow I will implement the provision script for the vagrant using them.

In these libraries, besides modularizing all the different tasks that are needed to install wazuh and elastic stack I have created 2 functions called elastic_stack_6 and elastic_stack_7 that installs the whole elastic stack for the different major versions. This will make possible to call these functions from the provision script as `elastic_stack_${ELASTIC_MAJOR}` which will make it easier to upgrade the script when a new major version of elastic is released.

Regards,
Daniel Folch.

**Comment by DFolchA** [comment]
Hello team,
I have finished writing the provision script and tested the ova generation for:
- [x]  wazuh 3.9.2 with elastic 7.1.1 
- [x]  wazuh 3.8.2 with elastic 6.7.1 
Regards,
Daniel Folch

**Comment by DFolchA** [comment]
Hello team, 

I have modified the libraries to remove all the `cat>` that were used to create configuration files, instead of this i have created a new directory called config_files that contains these files and the script just copies them from there.

This simplifies the scripts and makes them easier to understand and customize.

I have also run tests of the ova generate after these changes by connecting a 3.9.2 agent to the manager in the ova:

- [x]  wazuh 3.9.2 with elastic 7.1.1 
- [x]  wazuh 3.8.2 with elastic 6.7.1 

Regards, 
Daniel Folch

**Comment by DFolchA** [comment]
Hello team,

I am trying to fix an error with sed that causes the whole filebeat.yml file to be deleted and makes filebeat to not be able to work properly, this seems to be related with executing the sed order as part of the provision script for vagrant, as if I execute the same order manually in the machine it doesnt cause any problem, this should be fixed by today.

Regards, 
Daniel Folch

**Comment by DFolchA** [comment]
Hello team,

In the end we have decided to fix the sed problem by downloading the filebeat.yml file in the generate_ova.sh script and storing it within the Config_files directory and aplying the changes to activate the geoip outside vagrant. Then we copy it to the vagrant as the other  configuration files.

The new ova has been tested and is already ready.

Regards,
Daniel Folch

**Comment by DFolchA** [comment]
Hello team,

We have found that the vagrant synced folder is included in the ova after exporting the virtual machine, this shouldn't happen so we are working on deleting it, but we still need cause we use it to store some configuration files so I will try to send the files using scp instead of sharing the directory.

Regards, 
Daniel Folch
