### ISSUE TITLE
agent-4.2.3-1.msi log file errors explanation

### ISSUE THREAD

**Issue by mdiego92** [wazuh/wazuh-packages#1786]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.2.3-1 | Agent | Install | Windows 10 |

Hello! I would like to know what's the explanation of the error messages that appear in the **agent-4.2.3-1.msi** log file after the installation. I'm aware that the installation was successful. 

E.g.:
```
MSI (c) (30:3C) [14:03:50:744]: Note: 1: 2205 2:  3: Error 
MSI (c) (30:3C) [14:03:50:744]: Note: 1: 2262 2: AdminProperties 3: -2147287038 

```
**Reference**: When users install from the administrative image, the installation uses the saved values of the properties, rather than the values in the .msi file.
https://docs.microsoft.com/en-us/windows/win32/msi/adminproperties?redirectedfrom=MSDN

```
=== Logging stopped: 8/16/2022  11:42:52 ===
MSI (c) (C4:98) [11:42:52:141]: Note: 1: 1707 
MSI (c) (C4:98) [11:42:52:141]: Note: 1: 2205 2:  3: Error 
MSI (c) (C4:98) [11:42:52:141]: Note: 1: 2228 2:  3: Error 4: SELECT `Message` FROM `Error` WHERE `Error` = 1707 
MSI (c) (C4:98) [11:42:52:141]: Note: 1: 2205 2:  3: Error 
MSI (c) (C4:98) [11:42:52:141]: Note: 1: 2228 2:  3: Error 4: SELECT `Message` FROM `Error` WHERE `Error` = 1709 
MSI (c) (C4:98) [11:42:52:141]: Product: Wazuh Agent -- Installation completed successfully.
1707 Installation operation completed successfully.
1709 Product: [2] -- [3]

```
https://docs.microsoft.com/en-us/windows/win32/msi/windows-installer-error-messages

```

Action start 11:42:46: RegisterProduct.
MSI (s) (48:00) [11:42:46:528]: Note: 1: 2205 2:  3: Error 
MSI (s) (48:00) [11:42:46:528]: Note: 1: 2228 2:  3: Error 4: SELECT `Message` FROM `Error` WHERE `Error` = 1302 
MSI (s) (48:00) [11:42:46:528]: PROPERTY CHANGE: Adding ProductToBeRegistered property. Its value is '1'.
Action ended 11:42:46: RegisterProduct. Return value 1.
```

Most of the errors seem to be referring to the Internal Consistency Evaluators. I get that, for example, the 1707 error would mean that the Installation operation was completed successfully. Another one, the 1302 error would indicate: `Please insert the disk: [2]`

Log file: https://pastebin.com/scPqNg1E

I would like to receive some insight regarding these messages. Is there any way to receive these messages directly and avoid confusion or misunderstandings when receiving the log entries?

Thank you very much in advance for your help.

**Comment by okynos** [comment]
Hello @mdiego92,

I have reviewed your report. I could conclude that there are some points to check inside our WXS template. Probably various of these `Note` fields could be removed by performing better management of the Windows Registry and policies.
We have to review as well the WXS Warnings that we get in the package generation steps.
I will open an issue inside the wazuh/wazuh repository to manage these messages.

By the way, I want to attach the installation command and the package URL tested:
- Installation command with verbose output `.\wazuh-agent-4.2.3-1.msi /lv verbose.log`
- Package URL: https://packages.wazuh.com/4.x/windows/wazuh-agent-4.2.3-1.msi
- Verbose log: [verbose.txt](https://github.com/wazuh/wazuh-packages/files/9401230/verbose.txt)

Thanks!

**Comment by okynos** [comment]
### Error codes
- `1402` -> Could not open key: [2]. System error [3].
- `2205` -> Database: [2]. Table does not exist: [3].
- `2262` -> Stream does not exist: [2]. System error: [3].
- `2898` -> For [2] textstyle, the system created a '[3]' font, in [4] character set.
- `2203` -> Database: [2]. Cannot open database file. System error [3].
- `2228` -> Database: [2]. Unknown table '[3]' in SQL query: [4].
- `2727` -> The directory entry '[2]' does not exist in the Directory table.
- `1715` -> Installed [2].
- `2265` -> Could not commit storage. System error: [3].
- `2318` -> File does not exist: [2].
- `1717` -> Removed [2].

### Note analysis
- `Note: 1: 1402 2: HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer 3: 2`
- `Note: 1: 2205 2:  3: Error`
- `Note: 1: 2262 2: AdminProperties 3: -2147287038`
- `Note: 1: 2898 2: MS Sans Serif 3: MS Sans Serif 4: 0 5: 20`
- `Note: 1: 1402 2: HKEY_CURRENT_USER\Software\Microsoft\MS Setup (ACME)\User Info 3: 2`
- `Note: 1: 2205 2:  3: PatchPackage`
- `Note: 1: 2203 2: C:\Windows\Installer\inprogressinstallinfo.ipi 3: -2147287038`
- `Note: 1: 2205 2:  3: LaunchCondition`
- `Note: 1: 2228 2:  3: LaunchCondition 4: SELECT ´Condition´ FROM ´LaunchCondition´`
- `Note: 1: 2205 2:  3: ActionText`
- `Note: 1: 2228 2:  3: Error 4: SELECT `Message` FROM `Error` WHERE `Error` = 2898`
- `Note: 1: 2262 2: Signature 3: -2147287038`
- `Note: 1: 1402 2: HKEY_LOCAL_MACHINE32\Software\Wazuh, Inc.\Wazuh Agent 3: 2`
- `Note: 1: 1402 2: HKEY_LOCAL_MACHINE32\System\CurrentControlSet\Services\OssecSvc 3: 2`
- `Note: 1: 1402 2: HKEY_LOCAL_MACHINE32\System\CurrentControlSet\Services\WazuhSvc 3: 2`
- `Note: 1: 2205 2:  3: MsiAssembly`
- `Note: 1: 2205 2:  3: Class`
- `Note: 1: 2205 2:  3: Extension`
- `Note: 1: 2205 2:  3: TypeLib`
- `Note: 1: 2205 2:  3: Patch`
- `Note: 1: 2205 2:  3: Condition`
- `Note: 1: 2228 2:  3: MsiAssembly 4:  SELECT ´MsiAssembly´.´Attributes´, ´MsiAssembly´.´File_Application´, ´MsiAssembly´.´File_Manifest´,  ´Component´.´KeyPath´ FROM ´MsiAssembly´, ´Component´ WHERE  ´MsiAssembly´.´Component_´ = ´Component´.´Component´ AND ´MsiAssembly´.´Component_´ = ? 
Action ended 11:09:44: CostFinalize. Return value 1.`
- `Note: 1: 2205 2:  3: _RemoveFilePath`
- `Note: 1: 2205 2:  3: BindImage`
- `Note: 1: 2205 2:  3: ProgId`
- `Note: 1: 2205 2:  3: PublishComponent`
- `Note: 1: 2205 2:  3: SelfReg`
- `Note: 1: 2205 2:  3: Font`
- `Note: 1: 2727 2:`
- `Note: 1: 1715 2: Wazuh Agent`
- `Note: 1: 2228 2:  3: Error 4: SELECT `Message` FROM `Error` WHERE `Error` = 1715`
- `Note: 1: 2898 2: MS Sans Serif 3: MS Sans Serif 4: 0 5: 16`
- `Note: 1: 2262 2: SourceHash 3: -2147287038`
- `Note: 1: 2265 2:  3: -2147287035`
- `Note: 1: 2318 2:`
- `Note: 1: 1402 2: HKEY_LOCAL_MACHINE32\SOFTWARE\ossec 3: 2`
- `Note: 1: 1402 2: HKEY_LOCAL_MACHINE32\Software\Microsoft\Windows\CurrentVersion\Uninstall\OSSEC 3: 2`
- `Note: 1: 2318 2: C:\Windows\Installer\1296c6.msi`
- `Note: 1: 1402 2: UNKNOWN\Products\603F581C73E7EB746A3CBF22194F881C\InstallProperties 3: 2`

### Related to the main issue
- `2205` + `1302` -> Related to Insert disk MSI Error message is not found. Reason: not defined in our Wazuh WXS file and MSI Error table, we could safely ignore. We will review to remove the message adding an Error description table inside the MSI, more information https://docs.microsoft.com/en-us/windows/win32/msi/windows-installer-error-messages?redirectedfrom=MSDN
- `2228` -> The same as the previous case. This error code only represent the full command requested.
- `PROPERTY CHANGE: Adding ProductToBeRegistered property. Its value is '1'.` and `Action ended 11:42:46: RegisterProduct. Return value 1.` It is related to the `ALLUSERS` variable that will register the product. It can be safely ignored due to expected register behaviour but. We will review in the WXS configuration to avoid the message.
