### ISSUE TITLE
Update deprecated apt-key add command in `wazuh-install.sh` script

### ISSUE THREAD

**Issue by DFolchA** [wazuh/wazuh-packages#1846]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.3 |` wazuh-install.sh` | Install | DEB |

## Objective

We need to adapt the `wazuh-install.sh` script to the changes proposed here:
https://github.com/wazuh/wazuh-packages/issues/1623#issuecomment-1239113879

By changing the use of apt-key command with:

```
 gpg --no-default-keyring --keyring gnupg-ring:/usr/share/keyrings/wazuh.gpg --import && chmod 644 /usr/share/keyrings/wazuh.gpg
```

## Validation tests

- [x] AIO in DEB system.
- [x] AIO in RPM system.
- [x] Distributed installation.

**Comment by verdx** [comment]
I have tried changing the command, there is yet to add the key location to the sources.list.d file for wazuh. I have had a lot of problems testing coming from branch 4.4, which doesn't work right now with production packages.

**Comment by verdx** [comment]
There was a problem, coming from 4.4, to test it, as the development branch took the package from `pre-release`, where there wasn't a 4.4 version. To test the changes related to this branch I first manually changed the repository used after creating `wazuh-install.sh` to use `staging` instead of `pre-release`. I then added an option to the `-d|--development` option in the `builder.sh`. If you run this script as `bash builder.sh -d staging`, it uses the `staging` repository to download the packages.

**Comment by verdx** [comment]
I tested for AIO in both DEB and RPM systems and it worked perfectly, but when I tested a distributed installation, I discovered there were some problems with Debian, coming from the 4.4 branch. Using Debian, the script freezes when trying to generate configuration files(`# bash wazuh-install.sh --generate-config-files`) and when trying to start the cluster after installing Wazuh Indexer(`# bash wazuh-install.sh --start-cluster`) Without solving this, I can't really prove the changes for apt-key are working correctly, so I am trying to fix this first.
