### ISSUE TITLE
`wazuh-install.sh` offline must improve the argument management when selecting rpm or deb

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-packages#1874]
The offline installation guide has the following section:
![image](https://user-images.githubusercontent.com/3830293/194229218-f267f5ea-8574-4a7e-84e9-74cf81aae4e8.png)

if a user copy, paste and run the command without following the Replace recommendation appears: 
```
root@alberpilot-test:/home/alberto_rodriguez/test# ./wazuh-install.sh -dw <deb|rpm>
bash: syntax error near unexpected token `newline'
```
The installation assistant should manage this situation, showing a descriptive error explaining that it is necessary to make a choice.

**Comment by davidcr01** [comment]
## Update Report

The Installation Assistant can not manage this situation because the generated error is not from the Installation Assistant itself, but the command prompt. The error is generated because the `>` and `<` characters are recognized as redirections, so it is not possible for the Installation Assistant to manage this. 

A possible solution is to change the related documentation and/or the help of the Installation Assistant.
