### ISSUE TITLE
The option to change the logo for custom branding is not working

### ISSUE THREAD

**Issue by c-bordon** [wazuh/wazuh-packages#1886]
# Description

When trying to make a customization in Wazuh dashboard and replace the Wazuh logos with custom logos, it was detected that the Logo of the landing page is not being changed:
![image](https://user-images.githubusercontent.com/64099752/195877211-8d3df46a-64cd-462b-8cd9-f9338e4a7c4f.png)
![image](https://user-images.githubusercontent.com/64099752/195877273-f9f996b3-05f8-44a5-ae6a-0917524d2680.png)

# Tasks
- [x] Analyze in the construction of the base that another way we can pass the Wazuh Logo without affecting the customization

# Validation
- [x] The new package must have the Wazuh logo by default and it must be possible to replace it with any svg image

**Comment by rauldpm** [comment]
## Update report

### Research

- The packages have been built to perform an AIO installation and try to reproduce the reported problem:
  - Revision: wp.1886
  - Repository: warehouse-test

|Package|Build|File|
|:--:|:--:|:--:|
|Wazuh dashboard app|https://devel.ci.wazuh.info/view/Packages/job/Packages_builder/8921/|[wazuh-4.4.0-wp.1886.zip](https://packages-dev.wazuh.com/warehouse/test/4.4/ui/dashboard/wazuh-4.4.0-wp.1886.zip)|
|Wazuh server|https://devel.ci.wazuh.info/job/Packages_builder/8923/|[wazuh-manager-4.4.0-wp.1886.x86_64.rpm](https://packages-dev.wazuh.com/warehouse/test/4.4/rpm/var/wazuh-manager-4.4.0-wp.1886.x86_64.rpm)|
|Wazuh indexer|https://devel.ci.wazuh.info/job/Packages_builder/8924/|[wazuh-indexer-4.4.0-wp.1886.x86_64.rpm](https://packages-dev.wazuh.com/warehouse/test/4.4/rpm/wazuh-indexer-4.4.0-wp.1886.x86_64.rpm)|
|Wazuh dashboard|https://devel.ci.wazuh.info/job/Packages_builder/8925/|[wazuh-dashboard-4.4.0-wp.1886.x86_64.rpm](https://packages-dev.wazuh.com/warehouse/test/4.4/rpm/wazuh-dashboard-4.4.0-wp.1886.x86_64.rpm)|
- The build of the Wazuh dashboard package has failed with the following error:

```
18:11:39  gzip: stdin: not in gzip format
18:11:39  tar: Child returned status 1
18:11:39  tar: Error is not recoverable: exiting now
```

- This error is usually due to not finding the Wazuh dashboard app in the AWS S3 bucket, in this case, but the generated Wazuh dashboard app file exits in the S3 bucket, upon investigation, this error may be due to a lack of updating the Docker image in AWS ECR.
- New images have been built and uploaded to AWS ECR.
- After updating the images, a new [build](https://devel.ci.wazuh.info/job/Packages_builder/8925/) has been launched which has finished successfully (See the table above).
- After an initial installation using the Wazuh dashboard package, it has been verified that the customization options offered by OpenSearch in the OpenSearch Dashboard configuration do not include the login screen logo, investigating the OpenSearch documentation the following has been found:
  - Documentation: https://opensearch.org/docs/latest/dashboards/branding/

|Setting|Corresponding branding element|
|:--:|:--:|
|logo|Header logo. See 1 in the image.|
|mark|OpenSearch Dashboards mark. See 2 in the image.|
|loadingLogo|Loading logo used when OpenSearch Dashboards is starting. See 3 in the image.|
|faviconUrl|Website icon. Loads next to the application title. See 4 in the image.|
|applicationTitle|The application's title. See 5 in the image.|

![image](https://user-images.githubusercontent.com/14913942/199596809-2547fbcd-a2c6-4a23-bea8-ba6ae6fec2ee.png)

- The inability to modify the login screen logo using the Wazuh dashboard package has been replicated in the OpenSearch Dashboards 2.3.0 package itself.

#### Information related to OpenSearch custom branding

- Branding customization development issue https://github.com/opensearch-project/OpenSearch-Dashboards/issues/725
  - The login screen logo is not included.
  - Associated PR: https://github.com/opensearch-project/OpenSearch-Dashboards/pull/826
- Issue opened by an OpenSearch user about the impossibility of modifying the login screen logo: https://github.com/opensearch-project/security-dashboards-plugin/issues/915, where an OpenSearch member mentions that said functionality was not contemplated in the development issue mentioned above.

```
By @peternied: Thanks @kgcreative it looks like we missed adding this customization logic into the login screen, thanks for referencing that pull request.
```

### Conclusion

- Due to what is reported in this comment, the possible actions to take are:
  - Modify the source files of the OpenSearch Dashboards package, for example, by using `sed` and adding a parameter to specify the file to use.
  - Wait for OpenSearch to include this functionality in another version.
  - Wait for the OpenSearch fork and include this functionality.

**Comment by alberpilot** [comment]
Blocked due: https://github.com/wazuh/wazuh-packages/issues/1886#issuecomment-1301244417

**Comment by rauldpm** [comment]
## Update report

- Working on the issue https://github.com/wazuh/wazuh-packages/issues/1907, a configuration has been found that can be applied in the `opensearch_dashboards.yml` file that allows direct access to the logo component so that it can be modified directly without the need to wait for OpenSearch to add such functionality in its branding customization.

```
opensearch_security.ui.basicauth.login.brandimage: "https://cdn-icons-png.flaticon.com/512/1/1601.png"
opensearch_security.ui.basicauth.login.title: "Custom image"
```

![Screenshot_20221103_153008](https://user-images.githubusercontent.com/14913942/199766547-fc390364-0b98-4355-a7d9-29c58d9915bf.png)

- Investigated the OpenSearch GitHub project, these configuration parameters have been located in the repository: https://github.com/opensearch-project/security-dashboards-plugin, in the file https://github.com/opensearch-project/security-dashboards-plugin/blob/main/public/types.ts
- The options that can be accessed directly are those defined in: https://github.com/opensearch-project/security-dashboards-plugin/blob/24807bb92ae9beaf06e03bf13cba74eca9c36603/public/types.ts#L43, specifically, for the logo from the login screen:

```
  ui: {
    basicauth: {
      login: {
        title: string;
        subtitle: string;
        showbrandimage: boolean;
        brandimage: string;
        buttonstyle: string;
      };
    };
```

- That said, after seeing this new configuration, and verifying that the construction of the package does not affect the change of the logos but that it is related to OpenSearch itself, no action is required on it.

**Comment by okynos** [comment]
All seems to be clear. If anyone wants to change the logo could use these indications.

Regards.
