### ISSUE TITLE
Black squared icon in Wazuh Dashboard

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-packages#1907]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.4.0-dev | Wazuh Dashboard | Install | Any |

Related issue: https://github.com/wazuh/wazuh-kibana-app/issues/4740

From @wazuh/frontend team, we're testing our plugin together with Wazuh Dashboard, using a test package provided by the @wazuh/cicd team.

We've seen that the platform has a visual bug, showing a black squared icon in the top left corner of the web app. This icon is the main logo, as seen [here](https://opensearch.org/docs/2.0/dashboards/branding/).

#### Wazuh app on Wazuh Dashboard 4.3.9 (based on OpenSearch Dashboards 1.2.0)
![image](https://user-images.githubusercontent.com/15186973/197756424-f274dc9d-9524-4380-a347-794dd0198082.png)

#### Wazuh app on OpenSearch 2.3.0
![image](https://user-images.githubusercontent.com/15186973/197756693-3cec963b-73f2-464d-a57a-7d3770e72f9f.png)

#### Wazuh app on Wazuh Dashboard 4.4.0 (based on OpenSearch Dashboards 2.3.0)
![image](https://user-images.githubusercontent.com/15186973/197756703-d5c3a888-0dd1-48f2-9f0b-cf41232c7feb.png)

**Comment by okynos** [comment]
Include research about how to eliminate the black square or how to define a top header with static color.

**Comment by rauldpm** [comment]
## Update report

### Research

- According to the OpenSearch documentation it is possible to modify this logo in the configuration of `opensearch_dashboards.yml` file: https://opensearch.org/docs/2.3/dashboards/branding/

### Test

- Created 1px svg image with transparency https://packages-dev.wazuh.com/resources/logo_app.svg
- Modified configuration as follow:

```
opensearchDashboards.branding:
   logo:
     defaultUrl: "https://packages-dev.wazuh.com/resources/logo_app.svg"
     darkModeUrl: "https://packages-dev.wazuh.com/resources/logo_app.svg"
```

- Before

![light_before](https://user-images.githubusercontent.com/14913942/199612480-266235ef-8332-4b69-9313-447548ebddf2.png)

![dark_before](https://user-images.githubusercontent.com/14913942/199612459-21894eef-2494-41e7-82a8-f3a0e59d22eb.png)

- After

![light_after](https://user-images.githubusercontent.com/14913942/199612476-9dbbfb01-73ef-4122-ba01-55add6124753.png)

![dark_after](https://user-images.githubusercontent.com/14913942/199612455-fc4c72d0-ceb3-40fe-8276-e5a5a511c947.png)


- When applying dark mode, it has been observed that the loading page shows a white crescent lying behind the Wazuh logo, the @wazuh/frontend team has been asked about it.

![image](https://user-images.githubusercontent.com/14913942/199612650-c223cb79-2ca8-46e2-9dc5-5b020900fc45.png)

- Although the image is hidden, a link continues to appear when hovering the cursor over the area where the black rectangle was, despite the fact that the image has a dimension of 1x1 pixel, it is possible that it is internally resized to a specific size.

![link](https://user-images.githubusercontent.com/14913942/199612721-71da133f-735d-48cd-8e5c-7c730547a86c.png)

### Next steps

- Investigate alternatives, such as removing said element from the WUI directly.
- A meeting with the team is necessary to decide what requirements this issue must have (It is desired to remove it completely, It is desired to give the option to modify the logo, etc.)

**Comment by rauldpm** [comment]
## Update report

### Research

- After talking with the team, it has been defined that the proposed fix is valid until the fork is made, so the proposed solution is maintained with a transparent image.
- Regarding the white half circle that can be seen on the loading screen in dark mode, it has been determined that it should not appear.
- The origin of this form has been investigated among the different files, apparently, this form is created through the `createElement` method in the `template.js` file, by removing the line `_react.default.createElement("circle",{fill :"#FFF",cx:"512",cy:"512",r:"512"}),`, said semicircle has disappeared.
- Regarding the logo of the Wazuh loading page, it has been detected that regardless of being in dark mode or not, it always has dark letters. The image used and where the image is used in the wazuh-packages files have not been located.

### Development

- The image used with a black square has been eliminated.
- Added an image with full transparency.
- The builder.sh file has been modified to use the new image, in addition, a new line has been added so that said image is also used in dark mode.

```
cp ./etc/custom_welcome/Assets/default_branding/logo_full_alpha.svg ./src/core/server/core_app/assets/default_branding/opensearch_logo_default_mode.svg
cp ./etc/custom_welcome/Assets/default_branding/logo_full_alpha.svg ./src/core/server/core_app/assets/default_branding/opensearch_logo_dark_mode.svg
```

![image](https://user-images.githubusercontent.com/14913942/199843520-75942f1f-cce6-44da-b32d-c462521000fe.png)
![image](https://user-images.githubusercontent.com/14913942/199843476-dbd78617-4050-436e-ad1b-b982331477bb.png)


- Removed the line `_react.default.createElement("circle",{fill:"#FFF",cx:"512",cy:"512",r:"512"}),` from the `template.js file`, now the page load shows the following:

![Screenshot_20221103_222401](https://user-images.githubusercontent.com/14913942/199843346-d36f2566-d757-4ec6-9bce-8035e089a910.png)
![Screenshot_20221103_222334](https://user-images.githubusercontent.com/14913942/199843355-3346f9a3-c8f0-4ce0-861f-2b63d56ec2bf.png)

### Next steps

- Investigate where the loading screen logo is set.
- Add a light image for the loading screen logo in dark mode
