### ISSUE TITLE
Windows agent upgrade could fail due to incorrect `ossec.conf` modifications

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-packages#1909]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.3.9-1 | Agent | Upgrade | Windows 2019 |

### Description
Occasionally it is possible to have an upgrade failed attempt due to an incorrect `ossec.conf` modification. The upgrade modified the `ossec.conf` file with an invalid format (elements not closed) and drive the upgrade into rollback. 

### Environment 
- 1 Wazuh manager v4.3.9 (Amazon Linux 2)
- 20 Windows agents v4.3.8 (Windows server 2019). 

### Steps 
Take into account that is rarely produced. The described steps could not reproduce the described error in all the attempts. 
1. API upgrade `/agents/upgrade?agents_list=all`.
2. Wait for the list of all agents with v4.3.8 version, missing one of them.

### Evidences

<details>
  <summary>upgrade.log</summary>

```
2022-10-26 13:44:51Z - Current version: v4.3.8.
2022-10-26 13:44:51Z - Generating backup.
2022-10-26 13:44:51Z - Backing up Wazuh home files.
2022-10-26 13:44:53Z - Searching Wazuh-Agent cached MSI through the registry.
2022-10-26 13:44:53Z - Backing up Wazuh-Agent cached MSI: "C:\Windows\Installer\1a2d5.msi".
2022-10-26 13:44:54Z - Trying to stop Wazuh service again. Remaining attempts: 5.
2022-10-26 13:44:56Z - Starting upgrade processs.
2022-10-26 13:44:57Z - Waiting for the Wazuh-Agent installation to end.
2022-10-26 13:44:59Z - Restarting Wazuh-Agent service.
2022-10-26 13:45:00Z - Installation finished.
2022-10-26 13:45:00Z - Process ID: 1100.
2022-10-26 13:45:20Z - Reading status file: .
2022-10-26 13:45:20Z - Upgrade failed: Restoring former installation.
2022-10-26 13:45:21Z - Performing the Wazuh-Agent uninstall using: "MsiExec.exe /X{C50019C4-068F-4D30-ACB2-574C8FFE21C8} /quiet".
2022-10-26 13:45:29Z - Excecuting former Wazuh-Agent MSI: ".\backup\1a2d5.msi".
2022-10-26 13:45:30Z - Waiting for the installation to end.
2022-10-26 13:45:33Z - Restoring former Wazuh-Agent home files.
2022-10-26 13:45:34Z - Current version: v4.3.8.
2022-10-26 13:45:34Z - Installing Wazuh service.
2022-10-26 13:45:34Z - Starting Wazuh-Agent service.
```

</details>

<details>
  <summary>installer.log</summary>

[installer.log](https://github.com/wazuh/wazuh-packages/files/9870814/installer.log)

</details>

<details>
  <summary>Relevant agent ossec.log</summary>

```
2022/10/26 13:44:54 wazuh-modulesd:syscollector: INFO: Module finished.
2022/10/26 13:44:54 wazuh-agent: INFO: Exit completed successfully.
2022/10/26 13:44:54 wazuh-agent: INFO: (1314): Shutdown received. Deleting responses.
2022/10/26 13:45:00 wazuh-agent: ERROR: (1226): Error reading XML file 'ossec.conf': XMLERR: End of file and some elements were not closed. (line 101).
2022/10/26 13:45:00 wazuh-agent: CRITICAL: (1215): No client configured. Exiting.
2022/10/26 13:45:00 wazuh-agent: INFO: Received exit signal. Starting exit process.
2022/10/26 13:45:00 wazuh-agent: INFO: Set pending exit signal.
```

</details>

<details>
  <summary>Relevant manager ossec.log</summary>

```
2022/10/26 13:46:05 wazuh-modulesd:agent-upgrade: INFO: (8164): Received upgrade notification from agent '3'. Error code: '2', message: 'Upgrade failed'
```

</details>

**Comment by DFolchA** [comment]
Builded custom WPK package that maintains the old configuration files after upgrading
https://s3.us-west-1.amazonaws.com/packages-dev.wazuh.com/trash/wpk/windows/wazuh_agent_v4.3.9-custom.wpk_windows.wpk

**Comment by alberpilot** [comment]
It looks like there is a race condition. 
In every test, the deployment (now with 40 agents) always had between 1 and 3 agents failing because 
```
ERROR: (1226): Error reading XML file 'ossec.conf': XMLERR: End of file and some elements were not closed. (line 101).
```
It was tried several WPKs, where the upgraded `ossec.conf`, the supposed malformed one, it keeps untouched. When those `ossec.conf` files were reviewed, it was noticed that all was ok. This leads us to think that a race condition occurred. 

After this [commit](https://github.com/wazuh/wazuh/commit/de624b77342d5a4ab2e745cd3272a4071e3fee4f) the test (40 agent deployment and upgrade) was repeated more than 10 times (400 WPK upgrades). The error couldn't be replicated. Before this commit, the error is reproduced in about 90% of tests.

**Comment by DFolchA** [comment]
## Update 

@alberpilot  determined that this issue was caused by a race condition, due to starting the service while the installation was still ongoing. This was proved by adding a short sleep before starting the service which caused all the upgrades to work properly.

Knowing this, we have investigated possible solutions:

1. Force the script to wait for the installation command to end by adding `/wait` here:
https://github.com/wazuh/wazuh/blob/b11826da861a82b6b8f01d3b3cf0b95cabd46ad2/src/win32/do_upgrade.ps1#L220
Reference: 
- https://devblogs.microsoft.com/setup/waiting-for-msiexec-exe-to-finish/

2. Change the [current](https://github.com/wazuh/wazuh/blob/de624b77342d5a4ab2e745cd3272a4071e3fee4f/src/win32/do_upgrade.ps1#L164-L170) way the script checks if the installation has finished for a more precise one by checking the version of the installed MSI using:
```
Get-WmiObject Win32_Product | Where Name -eq '<ProductName>' |Format-Table IdentifyingNumber, Name
```
Reference: 
- https://www.advancedinstaller.com/msi-retrieve-productcode.html
- https://stackoverflow.com/questions/29937568/how-can-i-find-the-product-guid-of-an-installed-msi-setup

3. As we did for the test we can just add a sleep after the installation to ensure the MSI has finished installing.

We have decided to go with the first option, which has been implemented in this commit:
https://github.com/wazuh/wazuh/commit/0517c7b2ef800e0181ef5bfce6653420ec50bf0b

With this we generated the following test packages:
https://s3.us-west-1.amazonaws.com/packages-dev.wazuh.com/trash/wpk/windows/wazuh_agent_v4.3.10-test.wait_windows.wpk
https://s3.us-west-1.amazonaws.com/packages-dev.wazuh.com/trash/windows/wazuh-agent-4.3.10-test.wait.msi

**Comment by alberpilot** [comment]
**Validation**
The generated WPK has been tested over 120 upgrades and no errors were found. After that, the original WPK was tested in a deployment with only 20 agents and the error occurred on the first attempt.

**Comment by DFolchA** [comment]
Blocked by: https://github.com/wazuh/wazuh-qa/issues/3576
