### ISSUE TITLE
Pre-built packages for ppc64le architecture 

### ISSUE THREAD

**Issue by junawaneshivani** [wazuh/wazuh-packages#195]
Hi all, I have been able to build the .deb package on ppc64le for wazuh version 3.8.2. However the lintian step shows 5 errors and 445 warnings. For reference I tried building the package on x86 and got similar results. Am I missing something  here?

For ppc64le:
```
$ ./generate_debian_package.sh -b v3.8.2 -s /root/Shivani/ -t manager -a ppc64le -r 1
N: 476 tags overridden (5 errors, 445 warnings, 26 info)
Finished running lintian.

WARNING generated by debuild:
Making debian/rules executable!

+ find /build_wazuh -name '*.deb' -exec mv '{}' /var/local/wazuh ';'
Package wazuh-manager_3.8.2-1_ppc64le.deb added to /root/Shivani/.
```

For x86:
```
$ ./generate_debian_package.sh -b v3.8.2 -s /root/Shivani/ -t manager -a amd64 -r 1 
N: 501 tags overridden (4 errors, 497 warnings)
Finished running lintian.

WARNING generated by debuild:
Making debian/rules executable!

+ find /build_wazuh -name '*.deb' -exec mv '{}' /var/local/wazuh ';'
Package wazuh-manager_3.8.2-1_amd64.deb added to /root/Shivani/.
```

I had previously created an issue [here](https://github.com/wazuh/wazuh/issues/3478)...

**Comment by BraulioV** [comment]
Hi @junawaneshivani,

This is a known issue. Most of the errors and warnings that you can see in the output of the building process are false positives. Here you can see a brief summary of these errors:
- `W: wazuh-manager: breaks-without-version xxxxxx-xxxxx`: We don't specify any version because the manager breaks with any of the specified packages.
- `E: wazuh-manager: python-script-but-no-python-dep var/ossec/bin/agent_groups`: the Python scripts from Wazuh until Wazuh v3.9.0 are compatible between Python 2 and Python 3 and they work as an extension of the main functionallity of the Wazuh Manager. We could add it as a _Recommended dependency_ but for simplicity and compatibility, we decided to not added it and reference the installation of Python in our docs. In Wazuh v3.9.0 we included the Python interpreter in the installation of Wazuh (https://github.com/wazuh/wazuh/blob/master/CHANGELOG.md#v390-2019-05-02), so we don't need to add Python as a dependency anymore.
- `W: wazuh-manager: script-not-executable var/ossec/framework/wazuh/xxxx.py`: these scripts belong to the Wazuh's framework. They are part of a `wazuh` Python module, so they are used and imported by the Python interpreter, which means they don't need execution scripts.
- `W: wazuh-manager: executable-not-elf-or-script var/ossec/packages_files/manager_installation_scripts/*` these scripts or files are imported by other .sh script during the postinstall script, so they need execution permissions.
- `W: wazuh-manager: description-too-long` and `E: wazuh-manager: extended-description-is-empty` in future release of Wazuh, we will add new and common description for each package provided by Wazuh, so this will be fixed in the future.

Hope it helps, and if you have any question, please, share it with us.

Regards.

**Comment by junawaneshivani** [comment]
Thanks @BraulioV for your quick and clear response. I am able to build the wazuh-manager and wazuh-agent .deb packages on ppc64le. I am facing some dependency related issues for wazuh-api which should be resolved soon. Will raise a PR once done.

**Comment by BraulioV** [comment]
Hi @junawaneshivani, I can't wait to see your PR! I'm quite curious about the changes that you made to build .deb packages for ppc64Ie!

Thank you so much for your contribution :smile:

**Comment by junawaneshivani** [comment]
@BraulioV I have raised a PR for power support #207. Thank you for your help.  :smiley:

**Comment by BraulioV** [comment]
@junawaneshivani it was a pleasure! Thank you so much for your contribution! Impressive work :smile:

**Comment by alberpilot** [comment]
I proceed to close this issue, thanks all for an excellent work!
