### ISSUE TITLE
Improve the use of the `curl` tool in scripts

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh-packages#1960]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| up to master | All | Install/Upgrade/Remove components that use curl | Unix-like |

## Description

Currently the use of `curl` tool in different available scripts (i.e installation) could lead to errors that are not properly handled or difficult to troubleshoot.
 
It's desirable to improve execution result checks to provide a better user experience

**Comment by davidcr01** [comment]
## Update Report

To aboard this problem, after talking with the team, we thought that it is a good idea to search for a `retry` option of the `curl` command and if it does not exist, create a function that simulates it.

Fortunately, the `curl` command has several options to perform this:
- `--max-time` X     (how long each retry will wait)
- `--retry` X         (it will retry X times)
- `--retry-delay` 0   (avoid the exponential backoff algorithm)
- `--retry-max-time` X (total time before it's considered failed)
- `--retry-all-errors` (you do not tolerate errors)

With this, we can retry a `curl` command and check if the file has been fetched, as these lines show:

https://github.com/wazuh/wazuh-packages/blob/4d40821890536f098fb1298be3492e4ff81ce98c/unattended_installer/install_functions/filebeat.sh#L11-L16

**Comment by davidcr01** [comment]
This issue goes to On Hold. Working on https://github.com/wazuh/wazuh-packages/issues/2000

**Comment by davidcr01** [comment]
This issue is still On Hold. Working on https://github.com/wazuh/wazuh-packages/issues/1850, on GitHub workflow.

**Comment by davidcr01** [comment]
## Update Report

After talking with the team, the options and values suggested are:
- `--max-time 300`, allowing 300 seconds to perform the whole operation. This value is used in some scripts of the repository.
- `--retry 15`, allowing 15 retries.
- `--retry-delay 5`, waiting 5 seconds between each delay.
- `--retry-max-time 20`, giving 20 seconds to start new attempts since the start of the operation.
- `--retry-all-errors`, allowing not to tolerate errors.

**Comment by davidcr01** [comment]
## Update comment

After talking with @DFolchA, it is very recommended to add a new option in the `curl` commands, `--retry-connrefused` option which retries the `curl` even if the connection is refused.

:green_circle: Test in AIO passed correctly:
<details><summary>Show log</summary>

```
root@vagrant:/home/vagrant# bash wazuh-install.sh -a -i -o
10/01/2023 11:40:35 INFO: Starting Wazuh installation assistant. Wazuh version: 4.5.0
10/01/2023 11:40:35 INFO: Verbose logging redirected to /var/log/wazuh-install.log
10/01/2023 11:40:41 INFO: --- Removing existing Wazuh installation ---
10/01/2023 11:40:41 INFO: Removing Wazuh manager.
10/01/2023 11:40:57 INFO: Wazuh manager removed.
10/01/2023 11:40:57 INFO: Removing Wazuh indexer.
10/01/2023 11:41:03 INFO: Wazuh indexer removed.
10/01/2023 11:41:03 INFO: Removing Filebeat.
10/01/2023 11:41:08 INFO: Filebeat removed.
10/01/2023 11:41:08 INFO: Removing Wazuh dashboard.
10/01/2023 11:41:18 INFO: Wazuh dashboard removed.
10/01/2023 11:41:18 INFO: Installation cleaned.
10/01/2023 11:41:18 WARNING: Hardware and system checks ignored.
10/01/2023 11:41:33 INFO: Wazuh development repository added.
10/01/2023 11:41:33 INFO: --- Configuration files ---
10/01/2023 11:41:33 INFO: Generating configuration files.
10/01/2023 11:41:34 INFO: Created wazuh-install-files.tar. It contains the Wazuh cluster key, certificates, and passwords necessary for installation.
10/01/2023 11:41:34 INFO: --- Wazuh indexer ---
10/01/2023 11:41:34 INFO: Starting Wazuh indexer installation.
10/01/2023 11:42:20 INFO: Wazuh indexer installation finished.
10/01/2023 11:42:20 INFO: Wazuh indexer post-install configuration finished.
10/01/2023 11:42:20 INFO: Starting service wazuh-indexer.
10/01/2023 11:42:39 INFO: wazuh-indexer service started.
10/01/2023 11:42:39 INFO: Initializing Wazuh indexer cluster security settings.
10/01/2023 11:42:49 INFO: Wazuh indexer cluster initialized.
10/01/2023 11:42:49 INFO: --- Wazuh server ---
10/01/2023 11:42:49 INFO: Starting the Wazuh manager installation.
10/01/2023 11:43:38 INFO: Wazuh manager installation finished.
10/01/2023 11:43:38 INFO: Starting service wazuh-manager.
10/01/2023 11:43:59 INFO: wazuh-manager service started.
10/01/2023 11:43:59 INFO: Starting Filebeat installation.
10/01/2023 11:44:11 INFO: Filebeat installation finished.
10/01/2023 11:44:14 INFO: Filebeat post-install configuration finished.
10/01/2023 11:44:14 INFO: Starting service filebeat.
10/01/2023 11:44:15 INFO: filebeat service started.
10/01/2023 11:44:15 INFO: --- Wazuh dashboard ---
10/01/2023 11:44:15 INFO: Starting Wazuh dashboard installation.
10/01/2023 11:45:15 INFO: Wazuh dashboard installation finished.
10/01/2023 11:45:15 INFO: Wazuh dashboard post-install configuration finished.
10/01/2023 11:45:15 INFO: Starting service wazuh-dashboard.
10/01/2023 11:45:16 INFO: wazuh-dashboard service started.
10/01/2023 11:45:52 INFO: Initializing Wazuh dashboard web application.
10/01/2023 11:45:52 INFO: Wazuh dashboard web application initialized.
10/01/2023 11:45:52 INFO: --- Summary ---
10/01/2023 11:45:52 INFO: You can access the web interface https://<wazuh-dashboard-ip>
    User: admin
    Password: vF3M.R3I5l.aBz4h.ZyNnSTCYYnRJcTz
10/01/2023 11:45:52 INFO: Installation finished.
root@vagrant:/home/vagrant# 
```
</details>

**Comment by davidcr01** [comment]
## Update Report

### Offline installation
While testing the offline installation I discovered an error in the download of the packages. Issue: https://github.com/wazuh/wazuh-packages/issues/2043

**Comment by davidcr01** [comment]
## Update Report

As the simple `curl` commands of the AIO installation worked as expected, I continued with the remodel of those `curl` commands inside loops. I noticed that some of them are not recommended to be modified. In this example, this `curl` command checks if the Indexer node is ready, and the `curl` command detects a transient error, but the exit code status is 0 (everything is ok)

<details><summary>Show log</summary>

```
16/01/2023 08:42:13 INFO: Wazuh indexer post-install configuration finished.
16/01/2023 08:42:13 INFO: Starting service wazuh-indexer.
16/01/2023 08:42:32 INFO: wazuh-indexer service started.
16/01/2023 08:42:32 INFO: Initializing Wazuh indexer cluster security settings.
+ curl -XGET https://127.0.0.1:9200/ -uadmin:admin -k --max-time 120
OpenSearch Security not initialized.+ echo 0
0
+ curl -XGET https://127.0.0.1:9200/ -uadmin:admin -k --max-time 120 --retry-connrefused --retry-delay 10 --retry 12
Warning: Transient problem: HTTP error Will retry in 10 seconds. 12 retries 
Warning: left.
Warning: Transient problem: HTTP error Will retry in 10 seconds. 11 retries 
Warning: left.
Warning: Transient problem: HTTP error Will retry in 10 seconds. 10 retries 
Warning: left.
Warning: Transient problem: HTTP error Will retry in 10 seconds. 9 retries 
Warning: left.
Warning: Transient problem: HTTP error Will retry in 10 seconds. 8 retries 
Warning: left.
Warning: Transient problem: HTTP error Will retry in 10 seconds. 7 retries 
Warning: left.
Warning: Transient problem: HTTP error Will retry in 10 seconds. 6 retries 
Warning: left.
Warning: Transient problem: HTTP error Will retry in 10 seconds. 5 retries 
Warning: left.
Warning: Transient problem: HTTP error Will retry in 10 seconds. 4 retries 
Warning: left.
Warning: Transient problem: HTTP error Will retry in 10 seconds. 3 retries 
Warning: left.
Warning: Transient problem: HTTP error Will retry in 10 seconds. 2 retries 
Warning: left.
Warning: Transient problem: HTTP error Will retry in 10 seconds. 1 retries 
Warning: left.
OpenSearch Security not initialized.OpenSearch Security not initialized.OpenSearch Security not initialized.OpenSearch Security not initialized.OpenSearch Security not initialized.OpenSearch Security not initialized.OpenSearch Security not initialized.OpenSearch Security not initialized.OpenSearch Security not initialized.OpenSearch Security not initialized.OpenSearch Security not initialized.OpenSearch Security not initialized.OpenSearch Security not initialized.
+ echo 0
0
```
</details>

The first command, `curl -XGET https://127.0.0.1:9200/ -uadmin:admin -k --max-time 120`, returns the output: `OpenSearch Security not initialized` and `0` as exit code.
The second command (the proposed one for the issue) `curl -XGET https://127.0.0.1:9200/ -uadmin:admin -k --max-time 120 --retry-connrefused --retry-delay 10 --retry 12` returns the same output duplicated 12 times (the number of retries) and the same exit code, but the `curl` is retried because of a transient code. With this example, is shown that there are some curls that may not be modified.

**Comment by davidcr01** [comment]
## Update Report

### Bug in Offline Installation

An error has been found while debugging the `curl` commands in the Offline Installation. The bug was related to the download of packages that did not exist although a check was being made.

1. **Scan stage.** The Offline Installation tries to download some initial packages with `-1` as revision.
```
manager_revision="1"
indexer_revision="1"
dashboard_revision="1"
```
And if they exist, the script tries to get the package of each type with the greater revision possible.

<details><summary>Show code snippet</summary>

```
while curl -s -o /dev/null -w "%{http_code}" "${manager_base_url}/${manager_package}" --max-time 300 --retry 5 --retry-delay 5 --retry-connrefused | grep -q "200"; do
    manager_revision=$((manager_revision+1))
    if [ "${package_type}" == "rpm" ]; then
      manager_rpm_package="wazuh-manager-${wazuh_version}-${manager_revision}.x86_64.rpm"
      manager_package="${manager_rpm_package}"
    else
      manager_deb_package="wazuh-manager_${wazuh_version}-${manager_revision}_amd64.deb"
      manager_package="${manager_deb_package}"
    fi
  done
  if [ "$manager_revision" -gt 1 ] && [ "$(curl -s -o /dev/null -w "%{http_code}" "${manager_base_url}/${manager_package}" --max-time 300 --retry 5 --retry-delay 5 --retry-connrefused )" -ne "200" ]; then
    manager_revision=$((manager_revision-1))
    if [ "${package_type}" == "rpm" ]; then
      manager_rpm_package="wazuh-manager-${wazuh_version}-${manager_revision}.x86_64.rpm"
    else
      manager_deb_package="wazuh-manager_${wazuh_version}-${manager_revision}_amd64.deb"
    fi
  fi
```
</details>


2. **Download stage.** The script downloads the scanned packages. In this stage is not checked whether the package exists or not.

<details><summary>Show code snippet</summary>

```
for package in "${packages_to_download[@]}"
  do

    package_name="${package}_${package_type}_package"
    eval "package_base_url=${package}_${package_type}_base_url"

    eval "curl -so ${dest_path}/${!package_name} ${!package_base_url}/${!package_name} --max-time 300 --retry 5 --retry-delay 5 --retry-connrefused"
    if [  "${PIPESTATUS[0]}" != 0  ]; then
        common_logger -e "The ${package} package could not be downloaded. Exiting."
        exit 1
    else
        common_logger "The ${package} package was downloaded."
    fi

  done
```
</details>

:warning: The bug case is, if any of the initial packages (`-1` revision) does not exist, the while returns `false` and the loop is skipped, and the package is downloaded in the **download stage** without any checks. 

```
> curl -w '%{http_code}' https://packages-dev.wazuh.com/pre-release/yum/wazuh-manager-4.5.0-1.x86_64.rpm --max-time 300 --retry 5 --retry-delay 5       
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Key>pre-release/yum/wazuh-manager-4.5.0-1.x86_64.rpm</Key><RequestId>6Q3MARQCQGC32XS4</RequestId><HostId>6W2BVZqPvdSx3YDnw23sSu4KcJvH+F+wGMNLJm3UA9sb42Am1WHm0ii+Sz7Tu33njn/jY0hpL0w=</HostId></Error>404%   
                          
> echo $?                                              
0
```
The content of the package is a 404 error message, but the `curl` command exits with `0` as the code status.

:heavy_check_mark: The solution is to add a `--fail` parameter when the package is downloaded. This option makes the `curl` command display an error instead of the body of the HTTP request and returns `22` as the exit code status.

```
> curl  https://packages-dev.wazuh.com/pre-release/yum/wazuh-manager-4.5.0-1.x86_64.rpm --max-time 300 --retry 5 --retry-delay 5 --retry-connrefused --fail

curl: (22) The requested URL returned error: 404
> echo $? 
22
```

Now the execution is the expected behaviour:
```
+ eval 'curl -so wazuh-offline/wazuh-packages/wazuh-manager-4.5.0-1.x86_64.rpm https://packages-dev.wazuh.com/pre-release/yum/wazuh-manager-4.5.0-1.x86_64.rpm --max-time 300 --retry 5 --retry-delay 5 --retry-connrefused --fail'
++ curl -so wazuh-offline/wazuh-packages/wazuh-manager-4.5.0-1.x86_64.rpm https://packages-dev.wazuh.com/pre-release/yum/wazuh-manager-4.5.0-1.x86_64.rpm --max-time 300 --retry 5 --retry-delay 5 --retry-connrefused --fail
+ '[' 22 '!=' 0 ']'
+ common_logger -e 'The manager package could not be downloaded. Exiting.'
```

**Comment by davidcr01** [comment]
## Update Report

### Other curls - indexer.sh :orange_circle: 

- [x] indexer_startCluster (not modified)
https://github.com/wazuh/wazuh-packages/blob/af949072c34f176e3cc29dfd2bf2e26427a388a7/unattended_installer/install_functions/indexer.sh#L165
HTTP code: 503, so the proposed `curl` command retries.
- [x] indexer_startCluster (insert filebeat template in the node)

### Other curls - dashboard.sh

- dashboard_initialize
  - [x] Connect to the dashboard node. The loop can be removed and use the `curl` parameters
  https://github.com/wazuh/wazuh-packages/blob/af949072c34f176e3cc29dfd2bf2e26427a388a7/unattended_installer/install_functions/dashboard.sh#L101-L104

**Comment by davidcr01** [comment]
## Update Report

Currently working on automatic tests. I noticed some tests were failing due to the changed `curl` commands of the builder. The `builder.sh` may not be modified, as it uses the pre-installed version of `curl` and may not support the new parameters.

Also, I noticed that in Ubuntu 16.04 (xenial version), the `--retry-connrefused` parameter is not supported, as the highest version supported of `curl` is 7.47.0, and the new parameter was included in `7.58.0`. Instead of removing it and affect to all systems, I thought it would be great to make a code snippet that checks the `curl` version and add the `--retry-connrefused` only if it is supported.

**Comment by davidcr01** [comment]
## Update Report

After talking with the team, the proposed solution is to code a common function that executes the specified `curl` command with the `--retry-connrefused` if it is available, and if not, simulate the behavior of the `--retry-connrefused` option with a loop, fetching the `connection refused` curl error. 

The function may look like this:
```
function common_curl
  if --retry-connrefused is available
    curl $@ --retry-connrefused
  else
    while ...
      curl $@
    done
  fi
```
And it can be invoked, for instance, like `common_curl -XGET https://"${nodes_dashboard_ip}"/status -uadmin:"${u_pass}" -k -w %"{http_code}" -s -o /dev/null)"`

**Comment by davidcr01** [comment]
## Update Report

In the end, this is how the function looks like:


```
function installCommon_curl() {
    if [ -n "${connrefused}" ]; then
        eval "curl $@ --retry-connrefused"
        e_code="${PIPESTATUS[0]}"
    else
        retries=0
        eval "curl $@"
        e_code="${PIPESTATUS[0]}"
        while [ "${e_code}" -eq 7 ] && [ "${retries}" -ne 12 ]; do
            retries=$((retries+1))
            sleep 5
            eval "curl $@"
            e_code="${PIPESTATUS[0]}"
        done
    fi
    return "${e_code}"
}
``` 

Basically, the function executes the curl passed by arguments and adds the `--retry-connrefused` option if it is available. Notice that the `e_code` is returned as the script may use that code error. If this `return` statement is not added, the output always will be exit code `0`.

Some functions have been added to complement the above one:
- `checks_version`. A function that checks two versions passed by arguments, this function returns 0 if the first one is greater or equal to the second one, and 1 in other cases.
- `check_curlVersion`. A function that installs `curl` if it is not installed yet, gets the version of `curl` and checks if the `--retry-connrefused` option is available, using the function above.

**Comment by davidcr01** [comment]
## Update Report

### Escaping double quotes
With all changes applied, a problem was found while testing the AIO installation. It seems some `curl` commands with parameters that use `"` must be escaped because the function removes them when expanding the function arguments. To fix this, this double quotes must be escaped explicitly. This seems only to happen when using parameters that must use double quotes, such as `-H` option.

Some of these `curl` commands are:

https://github.com/wazuh/wazuh-packages/blob/3fd0c7d06abdfad81ad6b89ad690bcd6d37ad0a4/unattended_installer/install_functions/installCommon.sh#L101

https://github.com/wazuh/wazuh-packages/blob/3fd0c7d06abdfad81ad6b89ad690bcd6d37ad0a4/unattended_installer/install_functions/installCommon.sh#L116

https://github.com/wazuh/wazuh-packages/blob/4d31762aa5fc1d69f9d0e699feedb6f439163370/unattended_installer/passwords_tool/passwordsFunctions.sh#L80

https://github.com/wazuh/wazuh-packages/blob/4d31762aa5fc1d69f9d0e699feedb6f439163370/unattended_installer/passwords_tool/passwordsFunctions.sh#L98

### Exit status when the function is in a pipeline

In the `indexer.sh` file, the insertion of the `wazuh-alerts` template must be splitted in two `eval` commands to make the right comparison of the exit code of the function.

```
eval "installCommon_curl --silent ${filebeat_wazuh_template} --max-time 300 --retry 5 --retry-delay 5" | eval "installCommon_curl -X PUT 'https://${indexer_node_ips[pos]}:9200/_template/wazuh' -H 'Content-Type: application/json' -d @- -uadmin:admin -k --silent --max-time 300 --retry 5 --retry-delay 5 ${debug}"
```

:green_circle: With these changes, AIO finish the installation correctly in a Ubuntu 16.04 system.

<details><summary>Show log</summary>

```
root@ubuntu-xenial:/home/vagrant# bash wazuh-install.sh -a -i -o
25/01/2023 13:10:19 INFO: Starting Wazuh installation assistant. Wazuh version: 4.5.0
25/01/2023 13:10:19 INFO: Verbose logging redirected to /var/log/wazuh-install.log
25/01/2023 13:10:20 INFO: --- Removing existing Wazuh installation ---
25/01/2023 13:10:20 INFO: Wazuh GPG key not found in the system
25/01/2023 13:10:20 INFO: Installation cleaned.
25/01/2023 13:10:20 WARNING: Hardware and system checks ignored.
25/01/2023 13:10:30 INFO: Wazuh development repository added.
25/01/2023 13:10:30 INFO: --- Configuration files ---
25/01/2023 13:10:30 INFO: Generating configuration files.
25/01/2023 13:10:35 INFO: Created wazuh-install-files.tar. It contains the Wazuh cluster key, certificates, and passwords necessary for installation.
25/01/2023 13:10:35 INFO: --- Wazuh indexer ---
25/01/2023 13:10:35 INFO: Starting Wazuh indexer installation.
25/01/2023 13:11:18 INFO: Wazuh indexer installation finished.
25/01/2023 13:11:18 INFO: Wazuh indexer post-install configuration finished.
25/01/2023 13:11:18 INFO: Starting service wazuh-indexer.
25/01/2023 13:11:40 INFO: wazuh-indexer service started.
25/01/2023 13:11:40 INFO: Initializing Wazuh indexer cluster security settings.
25/01/2023 13:11:50 INFO: Wazuh indexer cluster initialized.
25/01/2023 13:11:50 INFO: --- Wazuh server ---
25/01/2023 13:11:50 INFO: Starting the Wazuh manager installation.
25/01/2023 13:12:29 INFO: Wazuh manager installation finished.
25/01/2023 13:12:29 INFO: Starting service wazuh-manager.
25/01/2023 13:12:50 INFO: wazuh-manager service started.
25/01/2023 13:12:50 INFO: Starting Filebeat installation.
25/01/2023 13:12:56 INFO: Filebeat installation finished.
25/01/2023 13:12:58 INFO: Filebeat post-install configuration finished.
25/01/2023 13:12:58 INFO: Starting service filebeat.
25/01/2023 13:12:58 INFO: filebeat service started.
25/01/2023 13:12:58 INFO: --- Wazuh dashboard ---
25/01/2023 13:12:58 INFO: Starting Wazuh dashboard installation.
25/01/2023 13:13:43 INFO: Wazuh dashboard installation finished.
25/01/2023 13:13:43 INFO: Wazuh dashboard post-install configuration finished.
25/01/2023 13:13:43 INFO: Starting service wazuh-dashboard.
25/01/2023 13:13:43 INFO: wazuh-dashboard service started.
25/01/2023 13:14:18 INFO: Initializing Wazuh dashboard web application.
25/01/2023 13:14:18 INFO: Wazuh dashboard web application initialized.
25/01/2023 13:14:18 INFO: --- Summary ---
25/01/2023 13:14:18 INFO: You can access the web interface https://<wazuh-dashboard-ip>
    User: admin
    Password: 4psjWfgNHvYPY?RZ4Nzk1rIt*E2*EpQQ
25/01/2023 13:14:18 INFO: Installation finished.
root@ubuntu-xenial:/home/vagrant# 
```
</details>

**Comment by davidcr01** [comment]
## Update Report

The second `curl` command of https://github.com/wazuh/wazuh-packages/issues/1960#issuecomment-1396924662 has been modified. The `--fail` option has been added and, with this change, the check of the curl in case the indexer is not initialized is compared with the returned curl error. The change is equivalent. 

Previous conditional:
```if [ "${curl}" == *"OpenSearch Security not initialized."* ]; then```

Proposed conditional:
```elif [ "${exit_code}" -eq "22" ]; then```

**Comment by davidcr01** [comment]
## Summary

- Added `installCommon_curl` function, which executes the `curl` command passed by arguments (excluding `curl` word) and adds the `--retry-connrefused` if it's available. If not, the function performs the retries manually. This allows every system to perform the retries if the connection is refused, even if the curl parameter is not available.
- Added `check_versions` function, which compares two versions passed by arguments, and returns `0` if the first one is greater or equal to the second one and `1` in other cases. This function is used in `check_curlVersion` function.
- Added `check_curlVersion` function, which installs `curl` tool if it's not installed yet and compares the version of the `curl` tool with the version of curl where the `--retry-connrefused` option was added `(7.52.0)`

- In many `curl` commands, the `--fail` option has been added in order to fetch HTTP error responses. A bug in Offline installation has been solved with this option (https://github.com/wazuh/wazuh-packages/issues/1960#issuecomment-1386843786). This parameter avoids storing files with the wrong content.
- Double quotes are escaped in some `curl` commands that the `-H` option is used. This makes the curl executed in the `installCommon_curl` function keep the necessary double quotes.
- Added a condition in the `installCommon_addWazuhRepo` function which avoids importing the Wazuh GPG key with the wrong content. This check can avoid the beginning of the installation with the wrong GPG key.
