### ISSUE TITLE
Improve generation process for RPM package

### ISSUE THREAD

**Issue by jesuslinares** [wazuh/wazuh-packages#20]
The current script to build the RPM packages is too complex. It also needs other dependencies as `mock` and it takes too much time to build the packages.

Tasks to do:

- [x] Simplify the build script.
   - [x] Clean up the script.
   - [x] Improve the parameter handler.
   - [x] Remove all the unnecessary stuff to create a package. Remove everything else.
- [x] Remove `mock` from the build process. The installation and maintenance of `mock` is too hard. 
- [x] Use Docker containers to build the packages.
- [x] Make a script/tool to build and prepare the environment.
- [x] Create the Dockerfiles to build i386 and x86_64 rpm packages.
- [ ] Create the Dockerfiles to build i386 and x86_64 rpm legacy packages (CentOS 5 / RHEL 5).
- [x] The RPM packages must copy the CHANGELOG file from the sources, rather than the one in `rpmbuild/SOURCES`. 
- [x] The RPM packages must install the `wazuh-manager.init` and `wazuh-agent.init` files from the sources, rather than the one in `rpmbuild/SOURCES`. 
- [x] Add compatibility for previous Wazuh versions. This means that the new tool to build the rpm packages must be able to build all the Wazuh 3.x versions.
- [x] Add support to build the packages in different directories using rpm macros.
- [ ] Testing.

**Comment by BraulioV** [comment]
Hi team,

I just upload the new scripts and Dockerfiles to build the RPM packages. For now, you can build an RPM package in a CentOS 6 that can be installed in Fedora, CentOS, RHEL, Amazon Linux, Suse 12, etc., but I'm having some issues to build the Docker image for CentOS 5 with the CentOS 5 repositories.

For now, you only need `git` and `Docker` to build the packages.

**Comment by BraulioV** [comment]
In addition to what I said before, the RPM specs from previous versions need this changes:
- The RPM packages must copy the CHANGELOG file from the sources, rather than the one in rpmbuild/SOURCES.
- The RPM packages must install the wazuh-manager.init and wazuh-agent.init files from the sources, rather than the one in rpmbuild/SOURCES.

**Comment by BraulioV** [comment]
This commit 5e884a875ee5ad2e63db6a140bbc90cee255cc7e solves the previous comment.

In addition, I just added the RPM specs for 3.4.0 in this branch.

**Comment by BraulioV** [comment]
Hi team, 

I solved this two issues:
- [x] The RPM packages must copy the CHANGELOG file from the sources, rather than the one in `rpmbuild/SOURCES`. 
- [x] The RPM packages must install the `wazuh-manager.init` and `wazuh-agent.init` files from the sources, rather than the one in `rpmbuild/SOURCES`. 

in this commit: 5e884a875ee5ad2e63db6a140bbc90cee255cc7e.

Regards,
Braulio.

**Comment by BraulioV** [comment]
Hi team, 

right now, the Docker image to build the CentOS 5 packages for x86_64 works like a charm, but, I'm having some issues with the i386 image when linking the Wazuh binaries with the compiled OpenSSL in `src/external`.

For now, this image will have to wait in order to improve the RPM specs, so I made this PR (#28) to add this features.

Regards,
Braulio.
