### ISSUE TITLE
Disable expanded header by default

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh-packages#2011]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.4 | Dashboard | Install | - |

We want to disable the extended header in our default dashboard configuration so the black header does not appear, as we're not using it.

```
opensearchDashboards.branding:
  useExpandedHeader: false
```

Instead of this header with a top black bar:

![image](https://user-images.githubusercontent.com/2181918/209930891-42dfe07f-4556-48dc-9f88-b2ba68dd9f2b.png)

We want something without it:

![image](https://user-images.githubusercontent.com/2181918/209931141-fe47de48-c92a-497b-873e-dbbbfc30031f.png)

We also need to remove the default logo when using the above configuration from the css.

**Comment by c-bordon** [comment]
## Update Report

### Tasks
- The default value of the header is changed so that in this way it is hidden
- I'm working on replacing the opensearch logo on the home button, but I still can't do it

### Next steps
- Replace opensearch logo

![Screenshot_20221229_175500](https://user-images.githubusercontent.com/64099752/210010210-87d004a0-7e14-46d5-9262-2aebea154b75.png)
![Screenshot_20221229_175529](https://user-images.githubusercontent.com/64099752/210010248-df199bf4-bb83-4ddb-bca4-67eb7e3b0094.png)
