### ISSUE TITLE
OVA services (not necesary Wazuh services) sometimes doesn't start due to timeout using VMWare

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-packages#2030]
Regarding this Reddit user question: https://www.reddit.com/r/Wazuh/comments/107vup6/wazuhindexer_and_wazuhmanager_fails_with_timeout/ it's necessary to review and investigate the OVA using VMWare workstation. 
We need to determine why the OVA runs into some services timeout when using the VMWare workstation. As you can see in the thread, not necessarily Wazuh services produce the timeout but others like `polkit` or `tuned`.

**Comment by DanVrse** [comment]
Hi, 

I'm working on a Windows 10/11 PC with VMWare Workstation 16. Also currently trying to use the current version of Wazuh (v4.3) on 8GB RAM of memory and 4 Processors.

The documentation did mention that hardware virtualization was required, so I switched on the Virtual Machine Platform feature in Windows. Not sure if it will degrade on the VM's performance. 

Currently, it just starts out very slow (maybe cuz of my PC), and the wazuh-indexer and wazuh-manager always fails to become active because of timeout. Moreover, other services also activate and begin to fail, for the same reason as well.
![wazuh-error](https://user-images.githubusercontent.com/86759588/212215926-c2a7a9af-7d6d-4b33-887b-8c0929fc029a.jpg)


This

**Comment by teddytpc1** [comment]
We haven't seen this issue in the latest release tests.
