### ISSUE TITLE
Alpine package error during installation

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh-packages#2081]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| Current 4.4 | Agent | Install | Since Alpine 3.11 container|

# Description

During the installation of an [Alpine package generated from wazuh/wazuh 4.4 branch](https://packages-dev.wazuh.com/warehouse/test/4.4/apk/var/x86_64/wazuh-agent-4.4.0-r1234.apk) (newer than 4.4.0-beta1), it was found that the installation shows an error but ends successfully.

This could be related with https://github.com/wazuh/wazuh-packages/pull/2060

## Steps to reproduce
```
wget https://packages-dev.wazuh.com/warehouse/test/4.4/apk/var/x86_64/wazuh-agent-4.4.0-r1234.apk
apk add -v --allow-untrusted wazuh-agent-4.4.0-r1234.apk
```
## Current output
```
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
(1/8) Installing libintl (0.20.1-r2)
(2/8) Installing ncurses-terminfo-base (6.1_p20200118-r4)
(3/8) Installing ncurses-libs (6.1_p20200118-r4)
(4/8) Installing libproc (3.3.16-r0)
(5/8) Installing procps (3.3.16-r0)
(6/8) Installing libgcc (9.3.0-r0)
(7/8) Installing libstdc++ (9.3.0-r0)
(8/8) Installing wazuh-agent (4.4.0-r1234)
Executing wazuh-agent-4.4.0-r1234.pre-install
Executing wazuh-agent-4.4.0-r1234.post-install
ERROR: 18 errors updating directory permissions
Executing busybox-1.31.1-r11.trigger
OK: 22 packages, 153 dirs, 270 files, 25 MiB
```
## Exptected output
No `ERROR: 18 errors updating directory permissions`-like messages are shown

**Comment by DFolchA** [comment]
## Update

After investigating we have found the cause of this error in the source code of apk-tools:
https://git.alpinelinux.org/apk-tools/tree/src/database.c

Here we found the following:
```
void apk_db_update_directory_permissions(struct apk_database *db)
{
	struct apk_out *out = &db->ctx->out;
	struct apk_installed_package *ipkg;
	struct apk_db_dir_instance *diri;
	struct apk_db_dir *dir;
	struct hlist_node *dc, *dn;
	struct update_permissions_ctx ctx = {
		.db = db,
	};

	list_for_each_entry(ipkg, &db->installed.packages, installed_pkgs_list) {
		hlist_for_each_entry_safe(diri, dc, dn, &ipkg->owned_dirs, pkg_dirs_list) {
			dir = diri->dir;
			if (!dir->update_permissions) continue;
			if (!dir->seen) {
				dir->seen = 1;
				dir->mode = 0;
				dir->uid = (uid_t) -1;
				dir->gid = (gid_t) -1;
			}
			apk_db_dir_apply_diri_permissions(diri);
		}
	}
	apk_hash_foreach(&db->installed.dirs, update_permissions, &ctx);
	if (ctx.errors) apk_err(out, "%d errors updating directory permissions", ctx.errors);
}
```

From this, we inferred that the error appeared because some of the files installed by the package were modified or removed during the installation.

Following this line of thought we determined that the error was caused by this line in the `post-install` script:
https://github.com/wazuh/wazuh-packages/blob/d2def8a326a838b8f4b1e911c9adbf3b6cb2a6c3/alpine/SPECS/wazuh-agent/wazuh-agent.post-install#L17

This line was added to remove the files that are only used during the installation process from the final installation, so the Alpine Linux package would have the same behavior as RPM or DEB packages.

By removing this line the resulting package does not show the error but it leaves those files after finishing the installation:
```
alpine316:/home/vagrant# apk add --allow-untrusted wazuh-agent-4.4.0-r1.apk 
fetch https://mirrors.edge.kernel.org/alpine/v3.16/main/x86_64/APKINDEX.tar.gz
fetch https://mirrors.edge.kernel.org/alpine/v3.16/community/x86_64/APKINDEX.tar.gz
(1/5) Installing libproc (3.3.17-r1)
(2/5) Installing procps (3.3.17-r1)
(3/5) Installing libgcc (11.2.1_git20220219-r2)
(4/5) Installing libstdc++ (11.2.1_git20220219-r2)
(5/5) Installing wazuh-agent (4.4.0-r1)
Executing wazuh-agent-4.4.0-r1.pre-install
Executing wazuh-agent-4.4.0-r1.post-install
Executing busybox-1.35.0-r17.trigger
OK: 147 MiB in 102 packages
alpine316:/home/vagrant#
```
