### ISSUE TITLE
Indexer not yet initialized

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-packages#2095]
|Wazuh version|Install type|
|---|---|
| 4.4.0-rc1 | Demo environment| 

During the testing performed on https://github.com/wazuh/wazuh/issues/16152, we have found the following errors in the indexer node-1:

```
[2023-02-14T10:32:31,042][ERROR][o.o.s.a.BackendRegistry  ] [node-1] Not yet initialized (you may need to run securityadmin)
```

We need to investigate the reasons for this.

**Comment by DFolchA** [comment]
## Update

This error appears because wazuh-indexer tries to connect with the security plugin after starting the service, and this message is just an indication that the security plugin needs to be initialized for the wazuh-indexer to run.

Probably this error appeared when the indexer first started and before initializing the security plugin, check this page of the documentation for more information about the deployment process:
https://documentation.wazuh.com/current/installation-guide/wazuh-indexer/step-by-step.html#cluster-initialization

Related issues:
https://github.com/wazuh/wazuh-packages/issues/1968
https://github.com/wazuh/wazuh-packages/issues/1968
