### ISSUE TITLE
Cannot install macOS package on macOS Ventura 13.4

### ISSUE THREAD

**Issue by DFolchA** [wazuh/wazuh-packages#2205]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.4.2 | Agent | Install | macOS Ventura |

| Related issues/PR |
|---
| Documentation https://github.com/wazuh/wazuh-documentation/issues/6123|
| Packages https://github.com/wazuh/wazuh-packages/pull/2218 |
| Kibana app https://github.com/wazuh/wazuh-kibana-app/issues/5466|
| Core https://github.com/wazuh/wazuh/pull/17195 | 

We were notified that the macOS package cannot be installed on macOS Ventura 13.4 if integrity protection is enabled, resulting in the following error:
```
Could not set environment: 150: Operation not permitted while System Integrity Protection is engaged
```

Probably this is caused by a notarization error in the package binaries

### Tasks
- [x] Investigate the cause of the error and affected systems

### Validation
- [x] The package can be installed with integrity protection enabled

## Solution summary

- A temporary file called `/tmp/wazuh_envs` will be created before the proper installation command call. This file will contain Deployment variables defined by the user and will be ingested and erased during the installation process. The file owns to root user in order to avoid security issues.
- A string that will contain the concatenation of user Deployment Variables will be created and inserted using the `echo` command into  `/tmp/wazuh_envs`. The string specs
  - ` && `-separated concatenation of list of KEY='VALUE', being KEY the available development variables and VALUE the one specified by the user
  - will be between double quotes, while each of the deployment variables values will be between single quotes
  - Deployment variable values need to be escaped if double quotes exist

**Comment by jnasselle** [comment]
# Update

## Package background

- Package generation job: https://ci.wazuh.info/job/Packages_builder_macos/9779/
```
b87e895e5e95de04018e9788c6d5717a7a3ff58f4b93c880a20bf52a7a0903bf054cdaa70baf82117d493e106edbfdc4f006758218b56fd23d1e27968290d846  wazuh-agent-4.4.2-1.pkg
```
- Package: v4.4.2 released package https://packages.wazuh.com/4.x/macos/wazuh-agent-4.4.2-1.pkg

## Attempt to reproduce the issue

Trying on faster env to test this
```console
ec2-user@ip-172-31-46-65 ~ % sw_vers 
ProductName:		macOS
ProductVersion:		13.2.1
BuildVersion:		22D68
```
```console
ec2-user@ip-172-31-46-65 ~ % csrutil status
System Integrity Protection status: unknown (Custom Configuration).

Configuration:
	Apple Internal: disabled
	Kext Signing: enabled
	Filesystem Protections: disabled
	Debugging Restrictions: enabled
	DTrace Restrictions: enabled
	NVRAM Protections: enabled
	BaseSystem Verification: enabled

This is an unsupported configuration, likely to break in the future and leave your machine in an unknown state.
```
```console
ec2-user@ip-172-31-46-65 ~ % curl -LO  https://packages.wazuh.com/4.x/macos/wazuh-agent-4.4.2-1.pkg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 5549k  100 5549k    0     0   149M      0 --:--:-- --:--:-- --:--:--  180M
ec2-user@ip-172-31-46-65 ~ % shasum -a 512 wazuh-agent-4.4.2-1.pkg 
b87e895e5e95de04018e9788c6d5717a7a3ff58f4b93c880a20bf52a7a0903bf054cdaa70baf82117d493e106edbfdc4f006758218b56fd23d1e27968290d846  wazuh-agent-4.4.2-1.pkg
ec2-user@ip-172-31-46-65 ~ % pkgutil --check-signature wazuh-agent-4.4.2-1.pkg 
Package "wazuh-agent-4.4.2-1.pkg":
   Status: signed by a developer certificate issued by Apple for distribution
   Notarization: trusted by the Apple notary service
   Signed with a trusted timestamp on: 2023-05-12 15:57:24 +0000
   Certificate Chain:
    1. Developer ID Installer: Wazuh Inc (KLZK8P68R5)
       Expires: 2027-02-01 22:12:15 +0000
       SHA256 Fingerprint:
           A8 8F B5 40 D9 1F 9A 4C AF DC 57 3F E7 7D 63 30 38 A1 78 7D 1C 05 
           54 80 27 EA D4 B9 C6 47 7E 1E
       ------------------------------------------------------------------------
    2. Developer ID Certification Authority
       Expires: 2027-02-01 22:12:15 +0000
       SHA256 Fingerprint:
           7A FC 9D 01 A6 2F 03 A2 DE 96 37 93 6D 4A FE 68 09 0D 2D E1 8D 03 
           F2 9C 88 CF B0 B1 BA 63 58 7F
       ------------------------------------------------------------------------
    3. Apple Root CA
       Expires: 2035-02-09 21:40:36 +0000
       SHA256 Fingerprint:
           B0 B1 73 0E CB C7 FF 45 05 14 2C 49 F1 29 5E 6E DA 6B CA ED 7E 2C 
           68 C5 BE 91 B5 A1 10 01 F0 24

```

**Comment by jnasselle** [comment]
# Update

Since `launchctl getenv` /`launchctl setenv` is used for setting installing deployment variables and also for communicating upgrade status, this issue will be splitted 

- Fix deployment variables mechanism @jnasselle 
- Improve restart procedure on upgrade scenarios @DFolchA

**Comment by DFolchA** [comment]
## Update

Investigate how to remove the `lauchctl` commands from pre and postinstall scripts while maintaining the functionality.

Tested adding the following key:
```
<key>com.apple.rootless.install</key>
```
 In the SPEC file.

Also, investigate the usage of  pre and post upgrade scripts

**Comment by jnasselle** [comment]
# Update

Since `launchctl getenv` / `launchctl setenv` is not currently available to root user when SIP is enabled, we need to fix how [Deployment variables](https://documentation.wazuh.com/current/user-manual/deployment-variables/deployment-variables-macos.html) are populated into installation scripts.
On the other hand, `install` command does not populate regular environment variables into those installation scripts, so solutions should also discard this too.

## Possible solutions
### Solution 1: Custom environment file with an aux script

Create and distribute an aux script that takes well-defined environment variables available [here](https://documentation.wazuh.com/current/user-manual/deployment-variables/deployment-variables-macos.html)  and create a file that inner installer scripts will use as environment variable files

Usage example
```console
curl -so wazuh-agent.pkg https://packages.wazuh.com/4.x/macos/wazuh-agent-4.4.2-1.pkg && curl -so wazuh-agent.pkg https://packages.wazuh.com/4.x/wazuh_macos_envs.sh && chmod +x ./wazuh_macos_envs.sh  && WAZUH_MANAGER="192.168.1.10" WAZUH_AGENT_GROUP 'default'  ./wazuh_macos_envs.sh && sudo installer -pkg ./wazuh-agent.pkg -target /
```
#### Steps:
 1. Download the Wazuh agent: `curl -so wazuh-agent.pkg https://packages.wazuh.com/4.x/macos/wazuh-agent-4.4.2-1.pkg `
 2. Download the Wazuh macOS aux environment script `curl -so wazuh_macos_envs.sh https://packages.wazuh.com/4.x/wazuh_macos_envs.sh`
 3. Give execution privileges: `chmod +x ./wazuh_macos_envs.sh `
 4. Set environment variables and execute `wazuh_macos_envs.sh`, that will dump them to a env file:`WAZUH_MANAGER="192.168.1.10" WAZUH_AGENT_GROUP 'default'  ./wazuh_macos_envs.sh`
 5. Install the Wazuh agent: `sudo installer -pkg ./wazuh-agent.pkg -target /`

At the end of step 4, a new file with a well-known path (this is absolutely necessary since step 5 will need to read it to populate the environments into ossec.conf) like `/tmp/wazuh-env` with the following content

```
WAZUH_MANAGER='192.168.1.10'
WAZUH_AGENT_GROUP 'default'
```

Step 5 will read and source `/tmp/wazuh-env` file and use those environments, cleaning up it after usage

**NOTE**: this file could also be created as root to avoid unprivileged access 

### Solution 2:  Custom environment file with manually-created command line

This option is quite similar that the last one, creating a more unintuitive command line but without the needing of downloading a script

```console
curl -so wazuh-agent.pkg https://packages.wazuh.com/4.x/macos/wazuh-agent-4.4.2-1.pkg  && echo -n "WAZUH_MANAGER='192.168.1.10'\nWAZUH_AGENT_GROUP='default' > `/tmp/wazuh-env` && sudo installer -pkg ./wazuh-agent.pkg -target /
```
#### Steps:
 1. Download the Wazuh agent: `curl -so wazuh-agent.pkg https://packages.wazuh.com/4.x/macos/wazuh-agent-4.4.2-1.pkg `
 2. Create a file that will contain environment variables: `echo -n "WAZUH_MANAGER='192.168.1.10'\nWAZUH_AGENT_GROUP='default' > `/tmp/wazuh-env`
 3. Install the Wazuh agent: `sudo installer -pkg ./wazuh-agent.pkg -target /`

At the end of step 2, a new file with a well-known path (this is absolutely necessary since step 3 will need to read it to populate the environments into ossec.conf) like `/tmp/wazuh-env` with the following content

```
WAZUH_MANAGER='192.168.1.10'
WAZUH_AGENT_GROUP 'default'
```

Step 3 will read and source `/tmp/wazuh-env` file and use those environments, cleaning up it after usage

**NOTE**: this file could also be created as root to avoid unprivileged access

**Comment by DFolchA** [comment]
## Update

After talking with the team we decided to use temporal files remove the `launchctl` commands in the pre and post install scripts  the fix has been implemented in this branch:
https://github.com/wazuh/wazuh-packages/tree/2205-remove-launchctl

### Tests

Installation on macOS Ventura:
```
sh-3.2# installer -pkg wazuh-agent-4.4.3-2205.ventura.pkg -target /
installer: Package name is Wazuh Agent
installer: Installing at base path /
installer: The install was successful.
```

Upgrade in macOS Ventura:

```
sh-3.2# installer -pkg wazuh-agent-4.4.3-2205.ventura.pkg -target /
installer: Package name is Wazuh Agent
installer: Upgrading at base path /
installer: The upgrade was successful.

```
