### ISSUE TITLE
ImportError in Test Module due to urllib3 Version Compatibility

### ISSUE THREAD

**Issue by Dwordcito** [wazuh/wazuh-packages#2266]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.5.x-rev | Tests | Tests | Amazon Linux 2 / Ubuntu Xenial |

### Description

This issue involves resolving an `ImportError` that occurs while importing the test module `test_unattended.py`. The error message indicates that the urllib3 library requires OpenSSL version 1.1.1 or higher, but the 'ssl' module is currently compiled with OpenSSL version 1.0.2g, causing a version compatibility issue.

Issue related to these failed checks: https://github.com/wazuh/wazuh-packages/pull/2254

### Expected Outcome

After implementing the solution, the ImportError caused by the version compatibility between urllib3 and the 'ssl' module should be resolved. The test module should be able to import successfully without any ImportError.

### Errors found in pipelines

![image](https://github.com/wazuh/wazuh-packages/assets/14300208/edb622fb-83d0-4138-9146-95c476216e4b)
![image](https://github.com/wazuh/wazuh-packages/assets/14300208/40608f30-0110-4ca5-9251-ba0e008633b8)

`ubuntu-bionic`
```
The full traceback is:
20:20:56  WARNING: The below traceback may *not* be related to the actual failure.
20:20:56    File "/tmp/ansible_apt_payload_tsM_FC/ansible_apt_payload.zip/ansible/modules/packaging/os/apt.py", line 431, in package_status
20:20:56    File "/usr/lib/python2.7/dist-packages/apt/cache.py", line 294, in __getitem__
20:20:56      raise KeyError('The cache has no package named %r' % key)
20:20:56  fatal: [172.31.13.194]: FAILED! => {
20:20:56      "changed": false,
20:20:56      "invocation": {
20:20:56          "module_args": {
20:20:56              "allow_unauthenticated": false,
20:20:56              "autoclean": false,
20:20:56              "autoremove": false,
20:20:56              "cache_valid_time": 0,
20:20:56              "deb": null,
20:20:56              "default_release": null,
20:20:56              "dpkg_options": "force-confdef,force-confold",
20:20:56              "force": false,
20:20:56              "force_apt_get": false,
20:20:56              "install_recommends": null,
20:20:56              "name": [
20:20:56                  "python3.9",
20:20:56                  "python3.9-distutils"
20:20:56              ],
20:20:56              "only_upgrade": false,
20:20:56              "package": [
20:20:56                  "python3.9",
20:20:56                  "python3.9-distutils"
20:20:56              ],
20:20:56              "policy_rc_d": null,
20:20:56              "purge": false,
20:20:56              "state": "present",
20:20:56              "update_cache": true,
20:20:56              "upgrade": null
20:20:56          }
20:20:56      }
20:20:56  }
20:20:56  
20:20:56  MSG:
20:20:56  
20:20:56  No package matching 'python3.9' is available
```

`Unattended Distributed`
```
20:19:17  failed: [172.31.8.134] (item=attrs==21.1.0) => {
20:19:17      "ansible_loop_var": "item",
20:19:17      "changed": false,
20:19:17      "item": "attrs==21.1.0",
20:19:17      "rc": 127
20:19:17  }
20:19:17  
20:19:17  MSG:
20:19:17  
20:19:17  The module failed to execute correctly, you probably need to set the interpreter.
20:19:17  See stdout/stderr for the exact error
20:19:17  
20:19:17  
20:19:17  MODULE_STDERR:
20:19:17  
20:19:17  Warning: Permanently added '172.31.8.134' (ECDSA) to the list of known hosts.

20:19:17  /bin/sh: /usr/bin/python: No such file or directory
```

**Comment by jnasselle** [comment]
Related analysis: https://github.com/wazuh/wazuh-jenkins/issues/5074#issuecomment-1542584120

**Comment by c-bordon** [comment]
## Update report

I managed to fix the urllib3 problem by limiting the version it has to install, to be compatible with OpenSSL 1.0.2 with this the problem was corrected in the unattended tests.

- Red Hat 8: https://ci.wazuh.info/view/Tests/job/Test_unattended/4041/console
- Red Hat 7: https://ci.wazuh.info/view/Tests/job/Test_unattended/4040/console
- Ubuntu Focal: https://ci.wazuh.info/view/Tests/job/Test_unattended/4038/console
- Ubuntu Jammy: https://ci.wazuh.info/view/Tests/job/Test_unattended/4039/console
- Ubuntu Xenial: https://ci.wazuh.info/view/Tests/job/Test_unattended/4035/console
- Ubuntu Bionic: https://ci.wazuh.info/view/Tests/job/Test_unattended/4045/console
- Centos 7: https://ci.wazuh.info/view/Tests/job/Test_unattended/4034/console
- Centos 8: https://ci.wazuh.info/view/Tests/job/Test_unattended/4036/console
- Amazon Linux 2: https://ci.wazuh.info/view/Tests/job/Test_unattended/4033/console


I'm still working on the bug in the unattended distributed tests: https://ci.wazuh.info/view/Tests/job/Test_unattended_distributed/492/console
