### ISSUE TITLE
Spike - Improve RPM SPEC file generation for Wazuh Dashboard and Wazuh Indexer

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh-packages#2396]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.7.0|  Dashboard/Indexer|Build |RPR-based |

It's desired to accomplish this according to https://github.com/wazuh/internal-devel-requests/issues/197 roadmap

# Description

This issue aims to research about the possibility to improve and make a more dynamic and flexible RPM SPEC file for Wazuh Dashboard and Indexer

**Comment by jnasselle** [comment]
# Update

On hold due to https://github.com/wazuh/wazuh-qa/issues/4493

**Comment by jnasselle** [comment]
# Update

Due to https://github.com/wazuh/wazuh/issues/18858, the ETA will be moved to Sept15

**Comment by jnasselle** [comment]
# Update

Due to https://github.com/wazuh/wazuh-qa/issues/4524, the ETA will be moved to Oct20

**Comment by jnasselle** [comment]
# Conclusions

SPEC file allows wildcard `*` to add every file as-it, avoiding making permission or file specifications.

This is not a full solution since, from the last research, for each minor Open search version, there are more than file chances but major changes (configuration files location, version on files) that basically force us to make a manual bumping.

A partial solution is using this wildcard as much as we can to kind of regular files (*.jar, *.txt, *.properties). Here @rauldpm is doing it https://github.com/wazuh/wazuh-packages/commits/enhancement/2521-bump-dashboard

**Comment by jnasselle** [comment]
Moving this issue to 4.8.0 version due to https://github.com/wazuh/internal-devel-requests/issues/199

**Comment by rauldpm** [comment]
As @jnasselle mentions, this is being improved in the bump to 2.10.0, both for the Wazuh indexer and for the Wazuh dashboard.

The change involves having the following characteristics

- All files with a given extension have been renamed to `*.extension`
- Binary files and directories must be maintained in a specific way since there is the possibility that more files or directories exist in the said directory, and specifying `*` means applying it to all elements, whether binaries, configuration, or directories

This does not free us from having to make specific modifications in the following bumps, since we do not have control over the OpenSearch and OpenSearch Dashboard files, but it eliminates much of the work by eliminating references to specific versions of files and encompassing multiple files by extension

## Related


- https://github.com/wazuh/wazuh-packages/issues/2521
- https://github.com/wazuh/wazuh-packages/issues/2520
