### ISSUE TITLE
Building wazuhapp archive | git clone urls not working | ERROR Unknown flag(s) "--opensearch-dashboards-version="

### ISSUE THREAD

**Issue by mrmoley007** [wazuh/wazuh-packages#2531]
|Wazuh version 4.9.0 | Install type| Action performed|Platform|
|---|---|---|---|
| X.Y.Z-rev | wazuh-kibana-app.zip | Install/Upgrade/Remove | OS version ubuntu 20.04 |

Dear Team, 
I am trying to build the wazuhapp as per the documentation given : https://documentation.wazuh.com/current/development/packaging/generate-wazuh-kibana-app.html

But i encounter several issues as below :

-------------------------------------------------

Downloading package.json from wazuh-kibana app repository
+ curl https://raw.githubusercontent.com/wazuh/wazuh-kibana-app/4.5.3/plugins/main/package.json -o /tmp/package.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    14  100    14    0     0     24      0 --:--:-- --:--:-- --:--:--    24
++ python -c 'import json, os; f=open("/tmp/package.json"); pkg=json.load(f); f.close();\
                    print(pkg["version"])'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib64/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 342, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 4 (char 3)

--------------------------

I tried to curl the url but it gives a 404 error

Then i tried to add the repos locally and copied the two repos wazuh-dashboard-plugins and elastic-kibana as described in the code and build the environment variables and run the code locally instead of running inside a docker. But now a new issue comes out in 

wazuh-dasboard-plugins/plugins/main/package.json
---------------------------------------------

yarn run v1.22.19
$ node scripts/generate-build-version
opensearch_dashboards.json file has been saved with latest version number
$ yarn plugin-helpers build --opensearch-dashboards-version=$OPENSEARCH_DASHBOARDS_VERSION
$ node ../../scripts/plugin_helpers build --opensearch-dashboards-version=
ERROR Unknown flag(s) "--opensearch-dashboards-version="

  node ../../scripts/plugin_helpers build [...args]

  Copies files from the source into a zip archive that can be distributed for
  installation into production Kibana installs. The archive includes the non-
  development npm dependencies and builds itself using raw files in the source
  directory so make sure they are clean/up to date. The resulting archive can
  be found at:
  
    build/{plugin.id}-{kibanaVersion}.zip

  Command-specific options:
    --skip-archive        Don't create the zip file, just create the build/kibana directory
    --kibana-version, -v  Kibana version this plugin will be built for

--------------------------------------------

I checked the code and there is no flag such as --opensearch-dashboards-version in elastic-kibana/packages/kdn-plugin-helpers/src/cli.ts

So , Request the team to solve .

**Comment by davidcr01** [comment]
Hello.

In your logs, I can see that the package.json file is being fetched by the URL "https://raw.githubusercontent.com/wazuh/wazuh-kibana-app/4.5.3/plugins/main/package.json". I suppose that you are trying to build a 4.5.3 package.

If this is correct, then the URL is wrong. This error is generated because of a bad configuration of the command. As is said in the [documentation](https://documentation.wazuh.com/current/development/packaging/generate-wazuh-kibana-app.html), the tag or version for building a 4.5.3 package is `v4.5.3-7.10.2`:

```console
./generate_wazuh_app.sh -b v4.5.3-7.10.2 -s /wazuh-app -r 1
```

This is because the 4.5.3 branch does not exist in the repository. The option `-b` accepts a valid branch or tags. You can see the tags and branches in the following links
- https://github.com/wazuh/wazuh-dashboard-plugins/branches
- https://github.com/wazuh/wazuh-dashboard-plugins/tags

In this case, the correct URL is the following: https://raw.githubusercontent.com/wazuh/wazuh-kibana-app/v4.5.3-7.10.2/package.json

Please, remove the steps you made (the two copied repositories in the code), and edit the command with the correct parameters. Please refer to the documentation for more guidance.

Hope it helps.
