### ISSUE TITLE
Package tests fail due to missing wazuh-indexer package

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh-packages#2579]
Currently, the wazuh-indexer package is not found for installation, which causes all Distributed cases tests to fail.

The error:
```
No package wazuh-indexer-4.7.1 available.
Error: Nothing to do
02/11/2023 17:54:19 ERROR: Wazuh indexer installation failed.
02/11/2023 17:54:19 INFO: --- Removing existing Wazuh installation ---
```

**Comment by TomasTurina** [comment]
This is also happening with wazuh-dashboard package.

**Comment by rauldpm** [comment]
The packages can be built using the `Packages_builder` pipeline if needed, the test is owned by @wazuh/cicd as it using the WIA (Test_unattended, Test_unattended_distributed, Test_unattended_distributed_cases)

@wazuh/cicd Perhaps it would be necessary to consider creating an issue in order to create the packages before executing the tests.
