### ISSUE TITLE
Feature Request: Add Wazuh agent installer to Winget repository

### ISSUE THREAD

**Issue by zbalkan** [wazuh/wazuh-packages#2593]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| N/A | Agent | Install | N/A |

[Winget](https://github.com/microsoft/winget-cli) is a package manager for Windows being maintained by Microsoft. Therefore, it would be a feasible approach to enable the users manage agent updates through Winget.

There are community maintained versions of Wazuh agent in [the Winget repository](https://github.com/microsoft/winget-pkgs/tree/master/manifests/w/Wazuh/WazuhAgent) but it's better to make it a part of Wazuh packages release process.

**Comment by rauldpm** [comment]
Hello @zbalkan 

I've been looking at the repository and it seems like a very interesting idea.

On the other hand, I see that the packages are being marked with the `Wazuh, Inc.` publisher, and although we provide the package URL, we are not the ones providing the package through `Winget`. I believe that this is extremely dangerous for users since this contribution is made entirely from the community itself, and one might think that we were the ones who provided this means when that is not the case.

https://github.com/microsoft/winget-pkgs/blob/b1817cb9a207a5d61ab02c7b628af453c2082a46/manifests/w/Wazuh/WazuhAgent/4.4.0/Wazuh.WazuhAgent.locale.en-US.yaml#L7

I am going to elevate this issue so that decisions can be made about it, thank you very much for the request!

**Comment by havidarou** [comment]
It looks like this repository only has packages up until Wazuh 4.4.

**Comment by zbalkan** [comment]
This repository is community made. It's the responsibility of Wazuh Inc to provide due diligence by accepting Winget as a source, removing Wazuh packages from unofficial repositories, or informing its user base that Winget packages are not the official resources. Ignoring the situation can be considered negligence.

**Comment by hex-m** [comment]
`4.7.5` is available now: https://github.com/microsoft/winget-pkgs/tree/master/manifests/w/Wazuh/WazuhAgent

**Comment by zbalkan** [comment]
That's an unofficial channel, so it is up to the users to trust and rely on the community provided packages.
