### ISSUE TITLE
Different vendor in RPM and DEB Wazuh packages

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh-packages#26]
When getting the packages list. There exists an inconsistency between deb and rpm packages.

While the deb package shows the following vendor:

```
"vendor": "Wazuh, Inc <support@wazuh.com>"
```

The rpm package shows the website instead of the company name.

```
"vendor": "https://www.wazuh.com"
```

**Comment by BraulioV** [comment]
Hi @chemamartinez,

this is fixed in https://github.com/wazuh/wazuh-packages/commit/53f6761fd063b2ae57083448855436f3f24cb489. What I have done is to set the _Vendor_ in the RPM specs to `"vendor": "Wazuh, Inc <support@wazuh.com>"`.

This commit will be merged to the master branch when this branch [dev-3.6.0-rpm-specs](https://github.com/wazuh/wazuh-packages/tree/dev-3.6.0-rpm-specs) gets merged.

Regards,
Braulio.
