### ISSUE TITLE
Investigate and fix failed checks from upward merge

### ISSUE THREAD

**Issue by MarcelKemp** [wazuh/wazuh-packages#2818]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.8.0 | Manager | Install | - |

## Description

Checks have failed on the next merge upward PR for a variety of reasons, although all of these changes have been merged into `4.8.0` - `Beta 1`:
- https://github.com/wazuh/wazuh-packages/pull/2814

We need to check the root of the problem and fix it so that the checks pass correctly.

### Error details

- [test-password-tool-success](https://github.com/wazuh/wazuh-packages/actions/runs/7815955726/job/21362553210#logs)
```
  wazuh-passwords-tool.sh: line 340: /var/ossec/bin/wazuh-keystore: No such file or directory
  Unauthorized401
  Error: Process completed with exit code 1.
``` 

- [All In One - Amazonlinux 2_base - Tests](https://github.com/wazuh/wazuh-packages/pull/2814/checks?check_run_id=21321133221)
- [All In One - Rhel 9 - Tests](https://github.com/wazuh/wazuh-packages/pull/2814/checks?check_run_id=21321156851)
- [Distributed Cases - manager_dashboard - centos - Tests](https://github.com/wazuh/wazuh-packages/pull/2814/checks?check_run_id=21321781529)
- [Distributed Cases - manager_indexer - ubuntu - Tests](https://github.com/wazuh/wazuh-packages/pull/2814/checks?check_run_id=21321905341)
```
indexer-connnector: ERROR: HTTP response code said error, status code: 401
```

## DoD

- [ ] Find the cause of the problems.
- [ ] Fix the issues encountered.
- [ ] Re-run the checks to verify that they are working correctly.

**Comment by tdrauncieal** [comment]
After an analysis of the logs provided by the related PR, it was found that the non-existence of the wazuh-keystore file is due to the fact that artifacts related to version `4.8.1` are being downloaded:
![image](https://github.com/wazuh/wazuh-packages/assets/93778492/3909393a-bbfb-43bb-bdf7-6cd747c7bb64)

in which case the nonexistence of the tool is to be expected since it is part of version `4.8.0`

**Comment by tdrauncieal** [comment]
The error reporting that the `wazuh-keystore` file does not exist was due to the fact that the package used for the installation, during the process, [wazuh-manager_4.8.1-1_amd64.deb](https://packages-dev.wazuh.com/staging/apt/pool/main/w/wazuh-manager/wazuh-manager_4.8.1-1_amd64.deb), was outdated.

#### test Reference: [test-password-tool-success](https://github.com/wazuh/wazuh-packages/actions/runs/7815955726/job/21414502964)

However, the test persists returning an error, so the cause continues to be investigated.
