### ISSUE TITLE
The macOS package logs error messages after a system restart if the MANAGER_IP value is not defined

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh-packages#2876]
| Target version | Related issue | Related PR/dev branch |
|---|---|---|
| 4.8.0-beta2  | https://github.com/wazuh/wazuh/issues/22072  |  https://github.com/wazuh/wazuh/tree/v4.8.0-beta2 |

## Description

The Test install for macos-12 ARM64 seems to be starting the system before the MANAGER_IP is configured. It could be an error on the tests or on the package side, the agent could be auto-starting after the installation, as reported on the issue https://github.com/wazuh/wazuh/issues/21636.

The log is new and does not comes from the package generation as we can validate by checking the timestamp:
```log
2024/02/28 07:18:47 wazuh-agentd: ERROR: (4112): Invalid server address found: 'MANAGER_IP'
```
the rest of the logs are from similar datetime
```log
2024/02/28 07:18:54 wazuh-execd: INFO: Started (pid: 576).
2024/02/28 07:18:55 wazuh-agentd: INFO: (1410): Reading authentication keys file.
```

Failing builds:
- https://ci.wazuh.info/job/Test_install/154329/console
- https://ci.wazuh.info/job/Test_install/154325/console

## Current behavior

The agent is being started before having the MANAGER_IP configured, the test `install_agent_test.py::test_check_log_errors` fails
```shellsession
12:20:31  install_agent_test.py:91: in test_check_log_errors
12:20:31      assert expected_error == True, assert_description['error']['exception_not_detected'] + " in line {}".format(line)
12:20:31  E   AssertionError: An error was found in the log in line 2024/02/28 07:18:47 wazuh-agentd: ERROR: (4112): Invalid server address found: 'MANAGER_IP'
12:20:31  E     
12:20:31  E   assert False == True
```

## Expected results

The agent should be started after the MANAGER_IP is configured

**Comment by vikman90** [comment]
## Problem Summary

### Action
- Install the package without defining `WAZUH_MANAGER`.
- Reboot the machine.

### Symptom
After system reboot, the error log is found in ossec.log, and the agent stops.

### Explanation
Unlike the Linux agent, where the service needs to be explicitly enabled (systemctl enable wazuh-agent), the macOS agent is configured to start automatically on the next reboot. If no IP for the manager is specified at that moment, an error is printed without significant consequences. This behavior is inconsistent with the Linux agent and deviates from the installation guide, which specifies the need to specify the manager's IP during installation.

### Options
a) Do nothing and adjust the test to follow the installation guide, considering the error is harmless.
b) Install the service disabled (<false />) and require the user to explicitly enable it:
    - :x: `launchctl enable -w /Library/LaunchDaemons/com.wazuh.agent.plist` (does not work)
    - :white_check_mark: Modify the file /Library/LaunchDaemons/com.wazuh.agent.plist.

Note: I have been unable to modify the file after accessing it; possibly due to SIP or an equivalent mechanism. Perhaps modifying the file after its creation is not a good idea.

## Issue status

This issue will remain **blocked** until the management team makes a decision. It's not a stopper IMO.

**Comment by davidjiglesias** [comment]
We agreed together with @havidarou this is a Low or Medium impact bug.

**Comment by vikman90** [comment]
The @wazuh/devel-qa's tests determined that the agent is restarting unexpectedly. This caused an error in the log, as the agent attempted to start before the manager's IP was configured. This is an expected error and has no impact.

Therefore, we will proceed to close this issue.
