### ISSUE TITLE
Packages [here](https://ossec.wazuh.com) maintained?

### ISSUE THREAD

**Issue by montdidier** [wazuh/wazuh-packages#29]
Are the packages [here](https://ossec.wazuh.com) still maintained? They do not appear to be, there are newer versions of ossec available than 2.8.3

**Comment by BraulioV** [comment]
Hi @montdidier ,

yes, it is still maintained. We are finishing some details about the OSSEC packages. We will upgrade the latest packages very soon.

Regards,
Braulio.

**Comment by montdidier** [comment]
Good to hear!

**Comment by montdidier** [comment]
@BraulioV I'd be happy to contribute to time, effort and skills to make this happen. Is there some way I can contribute?

**Comment by cbillett83** [comment]
I'm also still looking for an update on this. I don't have the knowledge to assist though :(

**Comment by snaow** [comment]
Hi @montdidier @cbillett83,

Sorry for late response and for the absence of follow-ups about this matter.
We have been really involved and focus on improving Wazuh capabilities, performance and reliability, we are about to release new version 3.7.0 which add, between others: Multithreading to the events process pipeline, getting agent configuration on-demand, agents multiple group assignments (find [here](https://documentation.wazuh.com/current/migrating-from-ossec/index.html) the full changelog)

Due to this, we could not allocate enough time to creating the Debian and RPM packages for OSSEC 3.0.0.

Since Wazuh every day is getting better as a product, I was wondering if you thought about migrating to Wazuh, keep in mind, your agents will still be compatible with the Wazuh manager.

I hope you can take a look into this brief document, which explain in detail why it's time to migrate from OSSEC.

- https://documentation.wazuh.com/current/migrating-from-ossec/index.html


If you need with the migration, we will be available as well on our [Slack workspace](https://goo.gl/forms/M2AoZC4b2R9A9Zy12) and the [community lists](https://groups.google.com/forum/#!forum/wazuh).


Regards,
Pedro.

**Comment by alberpilot** [comment]
Hello all

 We will finally not maintain the https://ossec.wazuh.com. We believe that we must focus on Wazuh installer improvements and support our community on those. I proceed to close this issue. 
 Don't hesitate to re-open again for any request or doubt. 

Regards, 
Alberto R
