### ISSUE TITLE
Support CentOS 9 in wazuh-install.sh

### ISSUE THREAD

**Issue by danieleperera** [wazuh/wazuh-packages#3016]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.8 | all in one | Install | CentOS Stream release 9 |

Add support to include centOS 9 in the installation.
Currently the wazuh-install.sh is missing to detect centOS 9, but by adding `&& [ "${DIST_VER}" -ne "9     " ];`  resolved and I was able to install all the components.

**Comment by davidcr01** [comment]
Hello.

Currently, the CentOS9 distribution is not listed as a recommended system in our documentation: https://documentation.wazuh.com/current/installation-guide/wazuh-server/index.html#recommended-operating-systems.
However, we are constantly adding more OS to this list in order to make the Wazuh installation assistant more widely used by the community. We also have [this](https://documentation.wazuh.com/current/installation-guide/wazuh-server/index.html#recommended-operating-systems) community where the recommended OS list will be updated, and so the Wazuh installation assistant.

Meanwhile, I recommend you to skip the OS check adding the `-i|--ignore` parameter to the command:
```
-i,  --ignore-check"
   Ignore the check for system compatibility and minimum hardware requirements."
```
