### ISSUE TITLE
Error at Indexer upgrade test

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh-packages#3031]
|Wazuh version|Install type|
|---|---|
| 4.8.1 → 4.9.0 | Indexer |

## Source

- https://github.com/wazuh/wazuh-packages/pull/3029
- https://github.com/wazuh/wazuh-packages/actions/runs/9842448384/job/27171394402?pr=3029

## Error

```
Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=container error was
14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"
```

**Comment by AlexRuiz7** [comment]
This test needs to be updated as it generated packages for `wazuh-indexer` using the tools from `wazuh-packages`. Since 4.9.0, all package are generated using the tools hosted in the repository of the component.

https://github.com/wazuh/wazuh-packages/blob/v4.9.0-alpha1/.github/workflows/test-indexer-rpm.yml

On the other hand, this test is prior the creation of the `wazuh-indexer` repository. We do not take ownership of these tests for the time being. However, we do smoke test the generated packages.

Taking a look at the workflow run, I identify 2 errors:

- An error related to a missing / unaccessible Centos repository:

    ```
    Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=container error was
    14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"
    ```

- An error related to a missing folder. Most likely due to the outdated package's generation:

    ```
    Cannot find a valid baseurl for repo: base/7/x86_64
    Error: the directory does not exist. /usr/share/wazuh-indexer/plugins/opensearch-security/securityconfig.
    ```

As final notes, I think this test needs to be skipped / disabled until we re-design it under the new packages generation process https://github.com/wazuh/internal-devel-requests/issues/187

**Comment by rauldpm** [comment]
Tests and repository code are pending removal from 4.9.0, we should ignore those tests.
