### ISSUE TITLE
Postinstall harmless error in macOS

### ISSUE THREAD

**Issue by BraulioV** [wazuh/wazuh-packages#307]
Hi team,

We've found an error in the macOS post-install script. Here you can see the output of the error from the file `/var/log/install.log`:
```
Sep 16 04:01:36 macos installd[647]: ./postinstall: cat: ./src/VERSION: No such file or directory
Sep 16 04:01:36 macos installd[647]: ./postinstall: cat: ./src/REVISION: No such file or directory
Sep 16 04:01:36 macos installd[647]: ./postinstall: grep: ./src/LOCATION: No such file or directory
```
This error related to the execution of the `gen_ossec.sh` script: https://github.com/wazuh/wazuh-packages/blob/a3a7b19048d6c0b1820785ec4a93ed64b09dbd03/macos/package_files/3.10.0/postinstall.sh#L73-L77

For now, this error doesn't affect the generation of the configuration files but it should be fixed in order to avoid problems related to this in a future.

**Comment by DFolchA** [comment]
Hello team, 
This issue was solved in this PR: #313 https://github.com/wazuh/wazuh-packages/blob/master/macos/package_files/3.10.2/build.sh#L61-L69

This error appeared because the darwin/18 directory was not created, this caused the build.sh script to fail and consequently, the following lines of the script were not executed so the VERSIO, REVISION and  LOCATION files were not copied into the package.

Regards,
Daniel Folch
