### ISSUE TITLE
wazuh-agent install fails on 14.04 and 16.04

### ISSUE THREAD

**Issue by alphaDev23** [wazuh/wazuh-packages#33]
The install output is below.  Why is the package install trying to access an invalid path and is there a fix?

$apt-get -y install wazuh agent

Setting up wazuh-agent (3.5.0-1) ...
chmod: cannot access ‘/var/ossec//src/init/replace_manager_ip.sh’: No such file or directory
dpkg: error processing package wazuh-agent (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 wazuh-agent
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by jesusgn90** [comment]
Hi @alphaDev23 ,

Thanks for your feedback, indeed we have a problem with some Debian related packages. I've opened another issue regarding to installation problems at https://github.com/wazuh/wazuh-packages/issues/32. Also I'm going to close this issue since you have https://github.com/wazuh/wazuh-packages/issues/35 opened and both problems come from same origin. Right now you have my issue (https://github.com/wazuh/wazuh-packages/issues/32) and your issue (https://github.com/wazuh/wazuh-packages/issues/35) to track this problem.

Regards,
Jesús

**Comment by alphaDev23** [comment]
The documentation should be updated to reflect the fact that Debian packages are untested.  There is no mention that apt-get packages are not tested or that it is broken at: https://documentation.wazuh.com/current/installation-guide/installing-wazuh-agent/wazuh_agent_deb.html

Hopefully, this comment will save others from wasting time trying to install untested packages using apt-get until #32 and #35 are resolved.
