### ISSUE TITLE
Please support architecture armhf

### ISSUE THREAD

**Issue by supersexy** [wazuh/wazuh-packages#365]
Seems like there are no packages for Raspian:
```
N: Skipping acquire of configured file 'main/binary-armhf/Packages' as repository 'https://packages.wazuh.com/3.x/apt stable InRelease' doesn't support architecture 'armhf'
```
That´s a problem. We have many Raspberries in our infra and this is a show stopper for Wazuh - it makes no sense to implement a security solution like Wazuh and leave out some percent of infra because no packages. Please support as many architectures as possible, thanks!

**Comment by supersexy** [comment]
Well, the installation [from sources](https://documentation.wazuh.com/3.10/installation-guide/installing-wazuh-agent/linux/debian7-or-greater/wazuh_agent_sources_debian7_or_greater.html#wazuh-agent-sources-debian7-or-greater) seems to work - why do not you provide packages if that works? 

However, I read in the install output: 
```
SCAP security policies are not available for this OS version.
```
Ao I just learned that there is no openscap for RaspberryPi!

**Comment by BraulioV** [comment]
Hi @supersexy,

As you found, we don't provide any official package for Raspbian but, Wazuh can be installed from sources without problems. To do so, you need to follow these steps:

1. Install the build dependencies: `apt-get update && apt-get install gcc make automake autoconf libtool curl python`
2. Download the repository: `curl -sL https://github.com/wazuh/wazuh/tarball/v3.10.2 | tar zx && mv wazuh* wazuh`
3. Build the agent: `cd wazuh && make -C src deps && make -C src TARGET=agent`
4. Install it using the install.sh

Once it is installed, you will have a completely functional agent. 

To avoid building the agent in each Raspberry Pi from your infrastructre, you can build the agent once, compress the sources repository using tar.gz or zip, distribute it in your infrastructure and install the agent using the install.sh script. To automate this, follow the steps from 1 to 3 and then, these new steps:
1. Build the agent following the steps from 1 to 3 from the previous list.
2. Modify the `preloaded-vars.conf` to automate the installation:
    ```shellsession
    echo 'USER_LANGUAGE="en"' > ./etc/preloaded-vars.conf
    echo 'USER_NO_STOP="y"' >> ./etc/preloaded-vars.conf
    echo 'USER_INSTALL_TYPE="agent"' >> ./etc/preloaded-vars.conf
    echo 'USER_DIR="/var/ossec"' >> ./etc/preloaded-vars.conf
    echo 'USER_DELETE_DIR="y"' >> ./etc/preloaded-vars.conf
    echo 'USER_ENABLE_ACTIVE_RESPONSE="y"' >> ./etc/preloaded-vars.conf
    echo 'USER_ENABLE_SYSCHECK="y"' >> ./etc/preloaded-vars.conf
    echo 'USER_ENABLE_ROOTCHECK="y"' >> ./etc/preloaded-vars.conf
    echo 'USER_ENABLE_OPENSCAP="y"' >> ./etc/preloaded-vars.conf
    echo 'USER_ENABLE_SYSCOLLECTOR="y"' >> ./etc/preloaded-vars.conf
    echo 'USER_ENABLE_CISCAT="y"' >> ./etc/preloaded-vars.conf
    echo 'USER_UPDATE="n"' >> ./etc/preloaded-vars.conf
    echo 'USER_AGENT_SERVER_IP="MANAGER_IP"' >> ./etc/preloaded-vars.conf
    echo 'USER_CA_STORE="/path/to/my_cert.pem"' >> ./etc/preloaded-vars.conf
    echo 'USER_AUTO_START="n"' >> ./etc/preloaded-vars.conf
    ```
    Thanks to this step, you can run the install.sh and install the agent completely unattended.
3. Compress the directory using `tar`: `cd .. && tar czf wazuh_v3.10.2.tar.gz wazuh` or using `zip`: `cd .. && zip -r wazuh_v3.10.2.zip wazuh`
4. Distribute the file from the previous step among your Raspberry Pi and uncompress it.
5. Run the install.sh script

Then, this message `SCAP security policies are not available for this OS version.` means that there are no available OpenSCAP policies for that OS, so they can't be installed and OpenSCAP doesn't support Rasbian as far as I know. Wazuh provides a native _Security Configuration Assesment_ module that you can use as the policy monitoring tool, so you don't need to install OpenSCAP or any other external tools. More information about this in https://documentation.wazuh.com/3.10/user-manual/capabilities/sec-config-assessment/index.html.

Answering to this question "_why do not you provide packages if that works?_": provide packages for more OS is in our roadmap. Wazuh works in Raspbian, BSD based systems, ArchLinux based systems, Gentoo, etc. but we don't provide any official packages yet, but we will do it as soon as we can.

I recommend you to join to our Slack channel: https://wazuh.com/community/join-us-on-slack/, because you can directly talk to us and is much faster than doing so through GitHub's issues.

Regards.

**Comment by supersexy** [comment]
Wow, thank you very much for this lovely answer and your attention! I totally appreciate your attention and understand the instructions, this was really lovely! 

The manual compilation works, as I tried myself, but this procedure of course rises new questions and problems. 

A) No signed package - this is a hard show stopper for a security tool! Installing it the way you described works, but makes it too easy for any attacker to replace the files that should warn about attackers - no way that should be done in production! 

B) I could now start signing the binaries and building some kind of infra to keep track of signatures... oh, wait, that _is_ a packaging system, we have that already, so reinventing the wheel is not needed (also no time budget for that kind of work).

C) Updates become painful - no `apt update` and, what is even worse, no handling of unattended-updates for quick security patches if that happens. On all production systems you absolutely want to avoid having this kind of manual handling. (No, we do not update everything unattended, but yes, only security updates).

So the next best solution would be to make this a `.deb` package - as the software compiles without errors and seems to work without any problems on Raspi, why not prioritize that last little step - you can announce Raspi support officially then and be one step ahead of other solutions! :)

**Comment by BraulioV** [comment]
Hi @supersexy,

Sorry for the super-late response, but I want to give you great news. We are working on adding new tools to build packages for `armhf` and `arm64` that will be used to provide official ports for ARM architecture. You can follow the changes in this branch [full-support-aarch64](https://github.com/wazuh/wazuh-packages/tree/full-support-aarch64). Right now using the tools from that branch you can create the following packages:
- Deb packages for `wazuh-manager`, `wazuh-agent` and `wazuh-api` for `armhf` and `arm64`.
- RPM packages for `wazuh-manager`, `wazuh-agent` and `wazuh-api` for `aarch64` and `armv7hl`.

We are currently testing these packages and testing the repositories containing them. Once we are done with testing and this branch gets merged into master, the next step will be to distribute official binary packages for ARM (both 32 and 64 bits) and add installation guidelines in [documentation.wazuh.com](https://documentation.wazuh.com).

I'll keep you updated with the changes and once we are ready to release these packages to production, we will announce it in our community channels.

Regards.

**Comment by Rohlik** [comment]
I tried use your build script for build ARM deb package but it failed with error:

`./generate_debian_package.sh -a armhf -t agent -b 3.10`
```
Sending build context to Docker daemon  7.168kB
Step 1/8 : FROM arm32v7/debian:stretch
 ---> b281f0b1a779
Step 2/8 : ENV DEBIAN_FRONTEND noninteractive
 ---> Using cache
 ---> 24bf27576490
Step 3/8 : RUN echo "deb http://deb.debian.org/debian/ stretch contrib main non-free" > /etc/apt/sources.list &&     echo "deb-src http://deb.debian.org/debian/ stretch contrib main non-free" >> /etc/apt/sources.list &&     apt-get update && apt-get install -y apt=1.4.9 apt-utils --allow-downgrades &&     apt-get install -y --force-yes     curl gcc make sudo expect gnupg fakeroot perl-base     perl libc-bin libc6 libc6-dev     build-essential cdbs devscripts equivs automake autoconf libtool     libaudit-dev selinux-basics util-linux libdb5.1     libssl1.1 libssl-dev gawk libsigsegv2 procps libc6-armel-cross
 ---> Running in b38fcd53ee27
standard_init_linux.go:178: exec user process caused "exec format error"
The command '/bin/sh -c echo "deb http://deb.debian.org/debian/ stretch contrib main non-free" > /etc/apt/sources.list &&     echo "deb-src http://deb.debian.org/debian/ stretch contrib main non-free" >> /etc/apt/sources.list &&     apt-get update && apt-get install -y apt=1.4.9 apt-utils --allow-downgrades &&     apt-get install -y --force-yes     curl gcc make sudo expect gnupg fakeroot perl-base     perl libc-bin libc6 libc6-dev     build-essential cdbs devscripts equivs automake autoconf libtool     libaudit-dev selinux-basics util-linux libdb5.1     libssl1.1 libssl-dev gawk libsigsegv2 procps libc6-armel-cross' returned a non-zero code: 1
```

Is it still in WIP or it should working?

**Comment by BraulioV** [comment]
Hi @Rohlik,

I think you're running the script in a x64 host. To build a package for `armhf` you need to run the script in aarch64 or armhf host. The image used to build the packages for `armhf` architecture is `arm32v7/debian:stretch` which can't be executed in an x64 host.

Here you can see a little guide to build packages depending on your target architecture:

**Build amd64 and i386** 

To build these packages, you need to run the following commands in a x64 host.
- Build the manager for amd64: `./generate_debian_package.sh -b v3.12.3 -t manager -a amd64`
- Build the agent for amd64: `./generate_debian_package.sh -b v3.12.3 -t agent -a amd64`
- Build the API for amd64: `./generate_debian_package.sh -b v3.12.3 -t api -a amd64`

In a x64 host, you can cross-compile the packages for i386 hosts:

- Build the manager for i386: `./generate_debian_package.sh -b v3.12.3 -t manager -a i386`
- Build the agent for i386: `./generate_debian_package.sh -b v3.12.3 -t agent -a i386`
- Build the API for i386: `./generate_debian_package.sh -b v3.12.3 -t api -a i386`

**Build aarch64**

To build thes packages , you need to run the following commands in a aarch64 host. For example, Amazon Linux in aarch64, Debian Buster arm64.
- Build the manager for aarch64: `./generate_debian_package.sh -b v3.12.3 -t manager -a aarch64`
- Build the agent for aarch64: `./generate_debian_package.sh -b v3.12.3 -t agent -a aarch64`
- Build the API for aarch64: `./generate_debian_package.sh -b v3.12.3 -t api -a aarch64`

**Build armhf**

To build these packages , you need to run the following commands in an armhf host. For example, a Raspberry Pi running Raspbian.
- Build the manager for armhf: `./generate_debian_package.sh -b v3.12.3 -t manager -a armhf`
- Build the agent for armhf: `./generate_debian_package.sh -b v3.12.3 -t agent -a armhf`
- Build the API for armhf: `./generate_debian_package.sh -b v3.12.3 -t api -a armhf`

* Note: aarch64 hosts can build these packages too using the flag: `-a armhf`. 

The tools to build `aarch64` and `armhf` from this repository are already merged in the master branch since we didn't detect any issues but we're still testing the packages for ARM to avoid any possible issue. They will be released in our repository with the release of Wazuh v3.13.0.

Regards.

**Comment by Rohlik** [comment]
Thank you so much!

**Comment by Corruptsector** [comment]
When i try and run the above i get these errors.

`ubuntu@AJW001-073404073403:~/wazuh-packages/debs$ sudo ./generate_debian_package.sh -b v3.12.3 -t agent -a aarch64
Sending build context to Docker daemon  7.168kB
Step 1/8 : FROM arm64v8/debian:stretch
 ---> 8f05e2b54f60
Step 2/8 : ENV DEBIAN_FRONTEND noninteractive
 ---> Using cache
 ---> d1e5b0d83c3f
Step 3/8 : RUN echo "deb http://deb.debian.org/debian stretch main contrib non-free" >> /etc/apt/sources.list &&     echo "deb-src http://deb.debian.org/debian stretch main contrib non-free" >> /etc/apt/sources.list &&     apt-get update && apt-get install -y apt=1.4.9 apt-utils --allow-downgrades &&     apt-get install -y --force-yes     curl gcc make sudo expect gnupg fakeroot perl-base perl wget     libc-bin libc6 libc6-dev build-essential     cdbs devscripts equivs automake autoconf libtool libaudit-dev selinux-basics     libdb5.3 libdb5.3 libssl1.0.2 gawk libsigsegv2
 ---> Running in ec3aa1949d2e
Get:1 http://security.debian.org/debian-security stretch/updates InRelease [94.3 kB]
Ign:2 http://deb.debian.org/debian stretch InRelease
Get:3 http://deb.debian.org/debian stretch-updates InRelease [93.6 kB]
Get:4 http://deb.debian.org/debian stretch Release [118 kB]
Get:5 http://deb.debian.org/debian stretch Release.gpg [2410 B]
Get:6 http://security.debian.org/debian-security stretch/updates/main arm64 Packages [510 kB]
Get:7 http://deb.debian.org/debian stretch-updates/main arm64 Packages [28.1 kB]
Get:8 http://deb.debian.org/debian stretch/contrib Sources [44.7 kB]
Get:9 http://deb.debian.org/debian stretch/non-free Sources [79.4 kB]
Get:10 http://deb.debian.org/debian stretch/main Sources [6753 kB]
Get:11 http://deb.debian.org/debian stretch/contrib arm64 Packages [39.9 kB]
Get:12 http://deb.debian.org/debian stretch/non-free arm64 Packages [50.8 kB]
Get:13 http://deb.debian.org/debian stretch/main arm64 Packages [6925 kB]
Fetched 14.7 MB in 5s (2809 kB/s)
Reading package lists...
W: Target Packages (main/binary-arm64/Packages) is configured multiple times in /etc/apt/sources.list:2 and /etc/apt/sources.list:7
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:2 and /etc/apt/sources.list:7
W: Target Packages (main/binary-arm64/Packages) is configured multiple times in /etc/apt/sources.list:2 and /etc/apt/sources.list:7
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:2 and /etc/apt/sources.list:7
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 apt-utils : Depends: apt (= 1.4.10) but 1.4.9 is to be installed
W: Target Packages (main/binary-arm64/Packages) is configured multiple times in /etc/apt/sources.list:2 and /etc/apt/sources.list:7
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:2 and /etc/apt/sources.list:7
E: Unable to correct problems, you have held broken packages.
The command '/bin/sh -c echo "deb http://deb.debian.org/debian stretch main contrib non-free" >> /etc/apt/sources.list &&     echo "deb-src http://deb.debian.org/debian stretch main contrib non-free" >> /etc/apt/sources.list &&     apt-get update && apt-get install -y apt=1.4.9 apt-utils --allow-downgrades &&     apt-get install -y --force-yes     curl gcc make sudo expect gnupg fakeroot perl-base perl wget     libc-bin libc6 libc6-dev build-essential     cdbs devscripts equivs automake autoconf libtool libaudit-dev selinux-basics     libdb5.3 libdb5.3 libssl1.0.2 gawk libsigsegv2' returned a non-zero code: 100
`

**Comment by BraulioV** [comment]
Hi @Corruptsector,

Thanks for the feedback. We just merged this PR https://github.com/wazuh/wazuh-packages/pull/438 into the master branch fixing the issue that you reported. In the PR description you can find more details about the changes.

Feel free to try the new changes and give us feedback. We really appreciate it.

Thanks again!

**Comment by BraulioV** [comment]
Hi all,

With just release Wazuh v3.13.0 and with it, official packages for `armhf` and `aarch64`. Those packages can be installed from our repositories following these guides:

## Wazuh Manager and Wazuh API
- [Installation guide for Debian](https://documentation.wazuh.com/3.13/installation-guide/installing-wazuh-manager/linux/debian/wazuh_server_packages_deb.html#wazuh-server-packages-deb).
- [Installation guide for RPM](https://documentation.wazuh.com/3.13/installation-guide/installing-wazuh-manager/linux/centos/wazuh_server_packages_centos.html#wazuh-server-packages-centos)

## Wazuh Agent
- [Installation guide for Debian](https://documentation.wazuh.com/3.13/installation-guide/installing-wazuh-agent/linux/debian7-or-greater/wazuh_agent_package_debian7_or_greater.html#wazuh-agent-package-debian7-or-greater).
- [Installation guide for RPM](https://documentation.wazuh.com/3.13/installation-guide/installing-wazuh-agent/linux/centos6-or-greater/wazuh_agent_package_centos6_or_greater.html#wazuh-agent-package-centos6-or-greater).

Also, you can find in our [packages-list](https://documentation.wazuh.com/3.13/installation-guide/packages-list/index.html#linux) the direct links to download the packages and their checksums.

I'm closing this issue, but, feel free to re-open it if you see it necessary, give us feedback or open a new issue. And also, I want to remind you that you can join our Slack channel https://wazuh.com/community/join-us-on-slack/ to ask questions or discuss with us in a more direct way.

Regards.
