### ISSUE TITLE
Add RHEL 8 FIPS mode compatibility

### ISSUE THREAD

**Issue by DFolchA** [wazuh/wazuh-packages#367]
Hello team,

We have found that due to this:
https://bugzilla.redhat.com/show_bug.cgi?id=1728031

The current packages cant be installed in RHEL 8 if FIPS mode is enabled, so we need to modify our package building method to fix this problem.

Regards, 
Daniel Folch

**Comment by BraulioV** [comment]
Hi all,

Currently, our RPM packages are built using RPM 4.8.0 in CentOS 6. This implementation of RPM adds a SHA1 header, a SHA1 digest, and no payload. Also, our current signing method relies on SHA1 as a digest algorithm. Here you can check our current v3.11.1 wazuh-manager package from our production repository:
```shellsession
rpm -v -K wazuh-manager-3.11.1-1.x86_64.rpm 
wazuh-manager-3.11.1-1.x86_64.rpm:
    Header V4 RSA/SHA1 Signature, key ID 29111145: NOKEY
    Header SHA1 digest: OK
    V4 RSA/SHA1 Signature, key ID 29111145: NOKEY
    MD5 digest: OK
```

[FIPS](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/6/html/security_guide/sect-security_guide-federal_standards_and_regulations-federal_information_processing_standard) add some security checks that make impossible to install our packages due to the package can't be verified because it doesn't have any digest. Check this below:
```
# rpm -ivh https://packages.wazuh.com/3.x/yum/wazuh-manager-3.11.1-1.x86_64.rpm
Retrieving https://packages.wazuh.com/3.x/yum/wazuh-manager-3.11.1-1.x86_64.rpm
Verifying...                                       ################################# [100%]
Preparing...                                       ################################# [100%]
	package wazuh-manager-3.11.1-1.x86_64 does not verify: no digest
```

RPM added the feature to add SHA256 digest in the latest releases that are not available in CentOS 6 unless you build them from sources.

So, to add FIPS support for our packages, I added the following modifications to the CentOS 6 Dockerfiles:
- Install all the `rpm` build-dependencies to build it from sources.
- Download, compile and install a newer version of `autoconf`, needed to build `rpm-4.15.1`.
- Download, compile and recompile a newer version of `libarchive`.
- Download a *custom* version of `rpm-4.15.1` with a fix for CentOS 6, compile it and install it. `rpm-4.15.1` has a bug in CentOS 6 that causes a segmentation fault due to a double free when `rpmbuild` is writing the binary `rpm` package. This error appears in a parallel OpenMP task. In this version, I just fixed 
that task.
- Changed the `entrypoint` script of the Dockerfiles to use the custom `rpmbuild` from the previous point to build the packages and to add two new macros: 
    - `%_source_filedigest_algorithm 8`
    - `%_binary_filedigest_algorithm 8`

    These macros add the SHA256 digest to our packages.
- Changed the signature method. Now, I added this custom command to sign our packages: 
```%__gpg_sign_cmd %{__gpg} gpg --force-v3-sigs --batch \ 
--verbose --no-armor --passphrase-fd 3 --no-secmem-warning \
-u "%{_gpg_name}" -sbo %{__signature_filename} \
--digest-algo sha256 %{__plaintext_filename}'```

With all of these changes, now we can build RPM packages with FIPS support. 

Regards.
