### ISSUE TITLE
Re-registration of agent does not replace broken "1969/12/31 20:00:00" registration date

### ISSUE THREAD

**Issue by branchnetconsulting** [wazuh/wazuh-packages#409]
|Wazuh version|Component|Install type|Install method|Platform|
|---|---|---|---|---|
| 3.12.0 | ossec-authd | Manager | n/a | n/a |

Apparently there was a bug in the wazuh-manager 3.11 upgrade process that wiped out the  **/var/ossec/queue/agents-timestamp** file that contains the registration dates for agents as seen under the Agents table in the Wazuh web UI.  The default behavior of the UI in the case of agents existing in the registration database but having no record in **agents-timestamp**, is to display the date "1969/12/31 20:00:00".

At present, when ossec-agentd performs a re-registration for an agent that is already registered, it fails to create a new line in **agents-timestamp** for the agent, which leaves the freshly re-registered agent displaying "1969/12/31 20:00:00" in the Agents table.  Please adjust the logic to handle the unexpected case of an existing agent not having a line in  **agents-timestamp**, so that their registration date gets successfully recorded.

Thanks,
Kevin Branch

**Comment by alberpilot** [comment]
Related: https://github.com/wazuh/wazuh-packages/issues/377

**Comment by BraulioV** [comment]
Hi all,

With the latest changes introduced in Wazuh 4.x this issue has been solved. Now, the file `/var/ossec/queue/agents-timestamp` is no longer used and the registration's timestamp is properly stored in `/var/ossec/queue/db/global.db`. I've been testing the re-registration of 4.x agents and the latest versions of 3.x and they work fine. Here you can see some tests:
- **Wazuh Manager 4.0.3 and Wazuh Agent 4.0.3**: 
![image](https://user-images.githubusercontent.com/9081114/102213577-3996b180-3ed7-11eb-9ad9-a590d454a364.png)
- **Wazuh Manager 4.0.3 and Wazuh Agent 3.13.2**: 
![image](https://user-images.githubusercontent.com/9081114/102213964-d6f1e580-3ed7-11eb-9d1a-c57f3a590cba.png)

For now, I'll close this issue since it was solved in the main repository [wazuh/wazuh](https://github.com/wazuh/wazuh). Feel free to reopen it if you have any doubts.
