### ISSUE TITLE
Wrong Ubuntu 18.04 agent purge

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-packages#46]
```
dpkg: atención: al desinstalar wazuh-agent, el directorio «/var/ossec/etc» no está vacío, por lo que no se borra
dpkg: atención: al desinstalar wazuh-agent, el directorio «/var/ossec/var/wodles» no está vacío, por lo que no se borra
```

**Comment by BraulioV** [comment]
Hi @jesusgn90 ,

this bug has been fixed in this commit https://github.com/wazuh/wazuh-packages/commit/5eeae4a8b1a25ac37f7e7489992f9e27f5555449. This issue will be closed automatically when [dev-3.6.1-debian-specs](https://github.com/wazuh/wazuh-packages/tree/dev-3.6.1-debian-specs) get merged into master.

Regards.
