### ISSUE TITLE
[Development] Wazuh daemons are still active after uninstalling DEB wazuh-agent.

### ISSUE THREAD

**Issue by jmv74211** [wazuh/wazuh-packages#491]
Hello team,

By doing installation and uninstallation tests I have observed that when uninstalling the `wazuh-agent`, the daemons are still active, as can be shown below:

![remove](https://user-images.githubusercontent.com/23462183/93076435-9fc92980-f687-11ea-856c-65ccfd87295e.gif)

It is requested to fix this.

### Related info

- Wazuh version: `4.0.0`
- Source branch: `fix-analysisd-add-logmsg-fail-cbdlist `
- Package url:  https://packages-dev.wazuh.com/warehouse/test/4.0/deb/var/wazuh-agent_4.0.0-jmv74211.error_amd64.deb

Best regards

**Comment by DFolchA** [comment]
Hello team,

This error appears if Wazuh is started using `ossec-control `instead of `systemctl`, doing this causes an inconsistency in the service where the daemons are running but the systemd service is stopped.

```
root@ubuntu18LTS-2:/home/vagrant# /var/ossec/bin/ossec-control start
Starting Wazuh v4.0.0...
Started ossec-execd...
Started ossec-agentd...
Started ossec-syscheckd...
Started ossec-logcollector...
Started wazuh-modulesd...
Completed.
root@ubuntu18LTS-2:/home/vagrant# systemctl status wazuh-agent
● wazuh-agent.service - Wazuh agent
   Loaded: loaded (/etc/systemd/system/wazuh-agent.service; disabled; vendor preset: enabled)
   Active: inactive (dead)

Sep 16 10:39:01 ubuntu18LTS-2 env[9535]: Completed.
Sep 16 10:39:01 ubuntu18LTS-2 systemd[1]: Started Wazuh agent.
Sep 16 10:40:11 ubuntu18LTS-2 systemd[1]: Stopping Wazuh agent...
Sep 16 10:40:11 ubuntu18LTS-2 env[11202]: Killing wazuh-modulesd...
Sep 16 10:40:11 ubuntu18LTS-2 env[11202]: Killing ossec-logcollector...
Sep 16 10:40:11 ubuntu18LTS-2 env[11202]: Killing ossec-syscheckd...
Sep 16 10:40:11 ubuntu18LTS-2 env[11202]: Killing ossec-agentd...
Sep 16 10:40:11 ubuntu18LTS-2 env[11202]: Killing ossec-execd...
Sep 16 10:40:11 ubuntu18LTS-2 env[11202]: Wazuh v4.0.0 Stopped
Sep 16 10:40:11 ubuntu18LTS-2 systemd[1]: Stopped Wazuh agent.
```

Then when running the pos-remove script `systemctl` founds the service is already in an inactive state so it does not stop it. For this reason, ossec-control must not be used unless strictly necessary and the services must be managed by systemd or upstart.

Regards,
Daniel Folch
