### ISSUE TITLE
Use cases testing new wazuh-indexer package

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-packages#704]
As part of the [Installer architecture simplification](https://github.com/wazuh/wazuh-packages/issues/665), and once verified the [technical viability](https://github.com/wazuh/wazuh-packages/issues/666), and finished [Wazuh Indexer SPECs](https://github.com/wazuh/wazuh-packages/issues/679) we must test the new Debian and RPM packages.

- [ ] Clean installation (oldest supported RPM and Deb OS and newer ones).
- [ ] Upgrade from an older wazuh-indexer build. 
- [ ] Installation with an existent elasticsearch working node.

**Comment by sbruno** [comment]
Did a quick test installing the RPM and DEB packages on Centos 7 and Debian stretch both having `opendistroforelasticsearch` installed, configured and running.

The packages used contains the changes of default ports from 9200 and 9300 to 9250 and 9350, and the change of opendistro-performance-analyzer service to wazuh-indexer-performance-analyzer

**Check existing elasticsearch installation:**

```
[root@host3 certs]# curl -XGET https://localhost:9200 -u admin:admin -k
{
  "name" : "node-1",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "BGzaoFncTYOQTOkK1JmJrw",
  "version" : {
    "number" : "7.10.0",
    "build_flavor" : "oss",
    "build_type" : "rpm",
    "build_hash" : "51e9d6f22758d0374a0f3f5c6e8f3a7997850f96",
    "build_date" : "2020-11-09T21:30:33.964949Z",
    "build_snapshot" : false,
    "lucene_version" : "8.7.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
```


**Install wazuh-indexer:**

```
[root@host3 certs]# cd /vagrant/
[root@host3 vagrant]# yum install ./wazuh-indexer-5.0.0-1.x86_64.rpm 
Loaded plugins: fastestmirror
Examining ./wazuh-indexer-5.0.0-1.x86_64.rpm: wazuh-indexer-5.0.0-1.x86_64
Marking ./wazuh-indexer-5.0.0-1.x86_64.rpm to be installed
Resolving Dependencies
--> Running transaction check
---> Package wazuh-indexer.x86_64 0:5.0.0-1 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

========================================================================================================================
 Package                    Arch                Version                Repository                                  Size
========================================================================================================================
Installing:
 wazuh-indexer              x86_64              5.0.0-1                /wazuh-indexer-5.0.0-1.x86_64              606 M

Transaction Summary
========================================================================================================================
Install  1 Package

Total size: 606 M
Installed size: 606 M
Is this ok [y/d/N]: y
Downloading packages:
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
Creating wazuh-indexer group... OK
Creating wazuh-indexer user... OK
  Installing : wazuh-indexer-5.0.0-1.x86_64                                                                         1/1 
### NOT starting on installation, please execute the following statements to configure wazuh-indexer service to start automatically using systemd
 sudo systemctl daemon-reload
 sudo systemctl enable wazuh-indexer.service
### You can start wazuh-indexer service by executing
 sudo systemctl start wazuh-indexer.service
Executing postinst
# Enabling opendistro performance analyzer to start and stop along with elasticsearch.service
Created symlink from /etc/systemd/system/wazuh-indexer.service.wants/wazuh-indexer-performance-analyzer.service to /usr/lib/systemd/system/wazuh-indexer-performance-analyzer.service.
Created elasticsearch keystore in /etc/wazuh-indexer/elasticsearch.keystore
  Verifying  : wazuh-indexer-5.0.0-1.x86_64                                                                         1/1 

Installed:
  wazuh-indexer.x86_64 0:5.0.0-1                                                                                        

Complete!
```

**Start Service**

```
[root@host3 vagrant]# systemctl daemon-reload
[root@host3 vagrant]# systemctl enable wazuh-indexer.service
Created symlink from /etc/systemd/system/multi-user.target.wants/wazuh-indexer.service to /usr/lib/systemd/system/wazuh-indexer.service.
[root@host3 vagrant]# systemctl start wazuh-indexer.service
```

**Initialize opendistro (using port 9350):**

```
[root@host3 vagrant]# JAVA_HOME=/usr/share/wazuh-indexer/jdk/ /usr/share/wazuh-indexer/plugins/opendistro_security/tools/securityadmin.sh -cn indexer-cluster -p 9350 -cd /usr/share/wazuh-indexer/plugins/opendistro_security/securityconfig/ -nhnv -cacert /etc/wazuh-indexer/certs/root-ca.pem -cert /etc/wazuh-indexer/certs/admin.pem -key /etc/wazuh-indexer/certs/admin-key.pem
Open Distro Security Admin v7
Will connect to localhost:9350 ... done
Connected as CN=admin,OU=Docu,O=Wazuh,L=California,C=US
Elasticsearch Version: 7.10.2
Open Distro Security Version: 1.13.1.0
Contacting elasticsearch cluster 'indexer-cluster' and wait for YELLOW clusterstate ...
Clustername: indexer-cluster
Clusterstate: GREEN
Number of nodes: 1
Number of data nodes: 1
.opendistro_security index does not exists, attempt to create it ... done (0-all replicas)
Populate config from /usr/share/wazuh-indexer/plugins/opendistro_security/securityconfig/
Will update '_doc/config' with /usr/share/wazuh-indexer/plugins/opendistro_security/securityconfig/config.yml 
   SUCC: Configuration for 'config' created or updated
Will update '_doc/roles' with /usr/share/wazuh-indexer/plugins/opendistro_security/securityconfig/roles.yml 
   SUCC: Configuration for 'roles' created or updated
Will update '_doc/rolesmapping' with /usr/share/wazuh-indexer/plugins/opendistro_security/securityconfig/roles_mapping.yml 
   SUCC: Configuration for 'rolesmapping' created or updated
Will update '_doc/internalusers' with /usr/share/wazuh-indexer/plugins/opendistro_security/securityconfig/internal_users.yml 
   SUCC: Configuration for 'internalusers' created or updated
Will update '_doc/actiongroups' with /usr/share/wazuh-indexer/plugins/opendistro_security/securityconfig/action_groups.yml 
   SUCC: Configuration for 'actiongroups' created or updated
Will update '_doc/tenants' with /usr/share/wazuh-indexer/plugins/opendistro_security/securityconfig/tenants.yml 
   SUCC: Configuration for 'tenants' created or updated
Will update '_doc/nodesdn' with /usr/share/wazuh-indexer/plugins/opendistro_security/securityconfig/nodes_dn.yml 
   SUCC: Configuration for 'nodesdn' created or updated
Will update '_doc/whitelist' with /usr/share/wazuh-indexer/plugins/opendistro_security/securityconfig/whitelist.yml 
   SUCC: Configuration for 'whitelist' created or updated
Will update '_doc/audit' with /usr/share/wazuh-indexer/plugins/opendistro_security/securityconfig/audit.yml 
   SUCC: Configuration for 'audit' created or updated
Done with success
```


**Check wazuh-indexer working (in port 9250)**

```
[root@host3 vagrant]# curl https://localhost:9250 -k -u admin:admin
{
  "name" : "node-1",
  "cluster_name" : "indexer-cluster",
  "cluster_uuid" : "x-eABMw0Q0G8rna6IR2FZQ",
  "version" : {
    "number" : "7.10.2",
    "build_flavor" : "oss",
    "build_type" : "rpm",
    "build_hash" : "747e1cc71def077253878a59143c1f785afa92b9",
    "build_date" : "2021-01-13T00:42:12.435326Z",
    "build_snapshot" : false,
    "lucene_version" : "8.7.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
```

**Check elasticsearch still responding:**

```
[root@host3 vagrant]# curl -XGET https://localhost:9200 -u admin:admin -k
{
  "name" : "node-1",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "BGzaoFncTYOQTOkK1JmJrw",
  "version" : {
    "number" : "7.10.0",
    "build_flavor" : "oss",
    "build_type" : "rpm",
    "build_hash" : "51e9d6f22758d0374a0f3f5c6e8f3a7997850f96",
    "build_date" : "2020-11-09T21:30:33.964949Z",
    "build_snapshot" : false,
    "lucene_version" : "8.7.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
```


**Check running java processes (4 processes: elasticsearch, opendistro performance analyzer, wazuh-indexer and wazuh-indexer performance analyzer)**

```
[root@host3 vagrant]# ps aux | grep java
elastic+  3552  2.0 34.3 3816856 1333384 ?     Ssl  23:16   0:32 /usr/share/elasticsearch/jdk/bin/java -Xshare:auto -Des.networkaddress.cache.ttl=60 -Des.networkaddress.cache.negative.ttl=10 -XX:+AlwaysPreTouch -Xss1m -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djna.nosys=true -XX:-OmitStackTraceInFastThrow -XX:+ShowCodeDetailsInExceptionMessages -Dio.netty.noUnsafe=true -Dio.netty.noKeySetOptimization=true -Dio.netty.recycler.maxCapacityPerThread=0 -Dio.netty.allocator.numDirectArenas=0 -Dlog4j.shutdownHookEnabled=false -Dlog4j2.disable.jmx=true -Djava.locale.providers=SPI,COMPAT -Xms1g -Xmx1g -XX:+UseG1GC -XX:G1ReservePercent=25 -XX:InitiatingHeapOccupancyPercent=30 -Djava.io.tmpdir=/tmp/elasticsearch-6921926119431632330 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/var/lib/elasticsearch -XX:ErrorFile=/var/log/elasticsearch/hs_err_pid%p.log -Xlog:gc*,gc+age=trace,safepoint:file=/var/log/elasticsearch/gc.log:utctime,pid,tags:filecount=32,filesize=64m -Dclk.tck=100 -Djdk.attach.allowAttachSelf=true -Djava.security.policy=file:///usr/share/elasticsearch/plugins/opendistro_performance_analyzer/pa_config/es_security.policy -XX:MaxDirectMemorySize=536870912 -Des.path.home=/usr/share/elasticsearch -Des.path.conf=/etc/elasticsearch -Des.distribution.flavor=oss -Des.distribution.type=rpm -Des.bundled_jdk=true -cp /usr/share/elasticsearch/lib/* org.elasticsearch.bootstrap.Elasticsearch -p /var/run/elasticsearch/elasticsearch.pid --quiet
elastic+  3554  4.2  3.9 2477388 153648 ?      Sl   23:16   1:06 /usr/share/elasticsearch/jdk/bin/java -Xshare:auto -Xms4m -Xmx64m -XX:+UseSerialGC -Dlog4j.configurationFile=/usr/share/elasticsearch/plugins/opendistro_performance_analyzer/pa_config/log4j2.xml -Xms64M -Xmx64M -XX:+UseSerialGC -XX:CICompilerCount=1 -XX:-TieredCompilation -XX:InitialCodeCacheSize=4096 -XX:InitialBootClassLoaderMetaspaceSize=30720 -XX:MaxRAM=400m -Des.path.home=/usr/share/elasticsearch -Des.path.conf=/etc/elasticsearch -Des.distribution.flavor=oss -Des.distribution.type=rpm -cp /usr/share/elasticsearch/lib/*:/usr/share/elasticsearch/performance-analyzer-rca/lib/* com.amazon.opendistro.elasticsearch.performanceanalyzer.PerformanceAnalyzerApp
wazuh-i+  5784  2.2 34.5 3817884 1340832 ?     Ssl  23:17   0:33 /usr/share/wazuh-indexer/jdk/bin/java -Xshare:auto -Des.networkaddress.cache.ttl=60 -Des.networkaddress.cache.negative.ttl=10 -XX:+AlwaysPreTouch -Xss1m -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djna.nosys=true -XX:-OmitStackTraceInFastThrow -XX:+ShowCodeDetailsInExceptionMessages -Dio.netty.noUnsafe=true -Dio.netty.noKeySetOptimization=true -Dio.netty.recycler.maxCapacityPerThread=0 -Dio.netty.allocator.numDirectArenas=0 -Dlog4j.shutdownHookEnabled=false -Dlog4j2.disable.jmx=true -Djava.locale.providers=SPI,COMPAT -Xms1g -Xmx1g -XX:+UseG1GC -XX:G1ReservePercent=25 -XX:InitiatingHeapOccupancyPercent=30 -Djava.io.tmpdir=/tmp/elasticsearch-13865157182851817290 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/var/lib/wazuh-indexer -XX:ErrorFile=/var/log/wazuh-indexer/hs_err_pid%p.log -Xlog:gc*,gc+age=trace,safepoint:file=/var/log/wazuh-indexer/gc.log:utctime,pid,tags:filecount=32,filesize=64m -Dclk.tck=100 -Djdk.attach.allowAttachSelf=true -Djava.security.policy=file:///usr/share/wazuh-indexer/plugins/opendistro-performance-analyzer/pa_config/es_security.policy -XX:MaxDirectMemorySize=536870912 -Des.path.home=/usr/share/wazuh-indexer -Des.path.conf=/etc/wazuh-indexer -Des.distribution.flavor=oss -Des.distribution.type=rpm -Des.bundled_jdk=true -cp /usr/share/wazuh-indexer/lib/* org.elasticsearch.bootstrap.Elasticsearch -p /var/run/wazuh-indexer/elasticsearch.pid --quiet
wazuh-i+  5786  2.2  3.6 2431272 140912 ?      Sl   23:17   0:33 /usr/share/wazuh-indexer/jdk/bin/java -Xshare:auto -Xms4m -Xmx64m -XX:+UseSerialGC -Dlog4j.configurationFile=/usr/share/wazuh-indexer/plugins/opendistro-performance-analyzer/pa_config/log4j2.xml -Xms64M -Xmx64M -XX:+UseSerialGC -XX:CICompilerCount=1 -XX:-TieredCompilation -XX:InitialCodeCacheSize=4096 -XX:InitialBootClassLoaderMetaspaceSize=30720 -XX:MaxRAM=400m -Des.path.home=/usr/share/wazuh-indexer -Des.path.conf=/etc/wazuh-indexer -Des.distribution.flavor=oss -Des.distribution.type=rpm -cp /usr/share/wazuh-indexer/lib/*:/usr/share/wazuh-indexer/performance-analyzer-rca/lib/* com.amazon.opendistro.elasticsearch.performanceanalyzer.PerformanceAnalyzerApp
root     13384  0.0  0.0  12528   976 pts/0    S+   23:42   0:00 grep --color=auto java
[root@host3 vagrant]# 
```

**Comment by sbruno** [comment]
Generated a wazuh-indexer version 4.2.0 for testing which contains elasticsearch 7.10 for testing the upgrade.

It worked correctly in RPM and DEB.

However it does not restart the service, so after installing it, still the old service is running.
This is the default behavior, but there is an environment variable that can be set for restarting automatically: `RESTART_ON_UPGRADE=true`
https://www.elastic.co/guide/en/elasticsearch/reference/master/rpm.html
https://www.elastic.co/guide/en/elasticsearch/reference/master/deb.html

When having that variable set, DEB installation succeeded but RPM installation failed to restart. Then it worked by manually restarting, so I'll check that, because possibly the code for restarting the service on upgrades with RESTART_ON_UPGRADE variable set may need to be moved to a different part of the post scripts.


**Debian:**

root@stretch:/vagrant# curl https://localhost:9250 -k -u admin:admin
{
  "name" : "node-1",
  "cluster_name" : "indexer-cluster",
  "cluster_uuid" : "TecTyUR1TAa9hr3fJD49HQ",
  "version" : {
    "number" : "7.10.0",
    "build_flavor" : "oss",
    "build_type" : "deb",
    "build_hash" : "51e9d6f22758d0374a0f3f5c6e8f3a7997850f96",
    "build_date" : "2020-11-09T21:30:33.964949Z",
    "build_snapshot" : false,
    "lucene_version" : "8.7.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}


root@stretch:/vagrant# apt-get install ./wazuh-indexer_5.0.0-1_amd64.deb 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'wazuh-indexer' instead of './wazuh-indexer_5.0.0-1_amd64.deb'
The following packages will be upgraded:
  wazuh-indexer
1 upgraded, 0 newly installed, 0 to remove and 68 not upgraded.
Need to get 0 B/422 MB of archives.
After this operation, 4,523 kB of additional disk space will be used.
Get:1 /vagrant/wazuh-indexer_5.0.0-1_amd64.deb wazuh-indexer amd64 5.0.0-1 [422 MB]
Reading changelogs... Done
(Reading database ... 27879 files and directories currently installed.)
Preparing to unpack .../wazuh-indexer_5.0.0-1_amd64.deb ...
Stopping wazuh-indexer service... OK
Unpacking wazuh-indexer (5.0.0-1) over (4.2.0-1) ...
Processing triggers for systemd (232-25+deb9u12) ...
Setting up wazuh-indexer (5.0.0-1) ...
Restarting wazuh-indexer service... OK
Executing postinst




root@stretch:/vagrant# curl https://localhost:9250 -k -u admin:admin
{
  "name" : "node-1",
  "cluster_name" : "indexer-cluster",
  "cluster_uuid" : "TecTyUR1TAa9hr3fJD49HQ",
  "version" : {
    "number" : "7.10.2",
    "build_flavor" : "oss",
    "build_type" : "deb",
    "build_hash" : "747e1cc71def077253878a59143c1f785afa92b9",
    "build_date" : "2021-01-13T00:42:12.435326Z",
    "build_snapshot" : false,
    "lucene_version" : "8.7.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}

**Comment by sbruno** [comment]
Kept doing some upgrade tests and adapting the package when some problem was found.

Currently I have two things left to analyze:

**1:**
As said before, there is an option to restart the service automatically after the package is upgraded. However this is not the default behavior.
If the package is upgraded and then the service is restarted manually there is no issue.

The way for enabling the automatic restart is by setting `RESTART_ON_UPGRADE=true` in `/etc/sysconfig/wazuh-indexer` for RPM systems or `/etc/default/wazuh-indexer` for DEB systems

In Debian it restarts correctly, but in Centos7 the service fails to start, and a jar hell error is displayed in the log:

```
Apr 15 20:07:37 host3 systemd-entrypoint[4651]: java.lang.IllegalStateException: jar hell!
Apr 15 20:07:37 host3 systemd-entrypoint[4651]: class: META-INF.versions.11.org.elasticsearch.core.internal.io.Streams
Apr 15 20:07:37 host3 systemd-entrypoint[4651]: jar1: /usr/share/wazuh-indexer/lib/elasticsearch-core-7.10.2.jar
Apr 15 20:07:37 host3 systemd-entrypoint[4651]: jar2: /usr/share/wazuh-indexer/lib/elasticsearch-core-7.10.0.jar
```

It looks like both elasticsearch versions of the jar file existed, but when checking if both files existed, only the newer was there.

Restarting the service manually after this works fine.
It looks like the service was restarted at some point when both files where there. Weird.
However this also happened on OpenDistro RPM and elasticsearch-oss RPM. To reproduce it in Centos7:

**Install older version of elsticsearch and start it:**
```
curl https://d3g5vo6xdbdb9a.cloudfront.net/yum/opendistroforelasticsearch-artifacts.repo -o /etc/yum.repos.d/opendistroforelasticsearch-artifacts.repo
export JAVA_HOME=/usr/ && yum install curl unzip wget libcap && yum install java-11-openjdk-devel
yum install -y elasticsearch-oss-7.10.0-1
systemctl daemon-reload
systemctl enable elasticsearch.service
systemctl start elasticsearch.service
```

**Check that service is running**

**Edit /etc/sysconfig/elasticsearch  and uncomment #RESTART_ON_UPGRADE=true**
`vi /etc/sysconfig/elasticsearch `

**Install newer version**
`yum install -y elasticsearch-oss-7.10.2-1`

**Check the last command output. Service does not start. Check service and logs.**


There is also a bug of this for elasticsearch: https://github.com/elastic/elasticsearch/issues/23785

But it is an old bug and was closed saying that it is not a problem of elasticsearch. Possibly is a combination with ODFE plugins, so it may be good to report or reopen the bug with more information.

**2:**
user and group were not removed when removing RPM with service up because they were used used by process XXX. However the process is stopped when uninstall finishes. The process seems to be always the performance analyzer. Didn't check it many times. Maybe some timing issue.

However this also seems to be happening with opendistro, but didn't happen only with elasticsearch-oss, so may confirm the cause is the performance analyzer:

```
Stopping elasticsearch service... OK
  Erasing    : elasticsearch-oss-7.10.2-1.x86_64                                                                  12/12 
warning: /etc/elasticsearch/jvm.options saved as /etc/elasticsearch/jvm.options.rpmsave
warning: /etc/elasticsearch/elasticsearch.yml saved as /etc/elasticsearch/elasticsearch.yml.rpmsave
Deleting log directory... OK
Deleting plugins directory... OK
userdel: user elasticsearch is currently used by process 4370
groupdel: cannot remove the primary group of user 'elasticsearch'

```

**Comment by sbruno** [comment]
Regarding the `RESTART_ON_UPGRADE` problem that is also present in elasticsearch, I added more information in the existing issue and created a new one since that one was closed: https://github.com/elastic/elasticsearch/issues/71784

The problem where user and group cannot be removed because they are in use is because the RPM removal scripts execute a `systemctl stop` of elasticsearch/wazuh-indexer and then removes the user and group, however it seems that even though the performance analyzer is a dependency and stops successfully with that same command, it takes some time, and is still up when the user and group are tried to be removed.


Here we can see elasticsearch and performance analyzer processes:
```
[root@host3 vagrant]# ps aux | grep java
elastic+  5339  115 33.6 3812256 1306852 ?     Ssl  04:58   0:12 /usr/share/elasticsearch/jdk/bin/java -Xshare:auto -Des.networkaddress.cache.ttl=60 -Des.networkaddress.cache.negative.ttl=10 -XX:+AlwaysPreTouch -Xss1m -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djna.nosys=true -XX:-OmitStackTraceInFastThrow -XX:+ShowCodeDetailsInExceptionMessages -Dio.netty.noUnsafe=true -Dio.netty.noKeySetOptimization=true -Dio.netty.recycler.maxCapacityPerThread=0 -Dio.netty.allocator.numDirectArenas=0 -Dlog4j.shutdownHookEnabled=false -Dlog4j2.disable.jmx=true -Djava.locale.providers=SPI,COMPAT -Xms1g -Xmx1g -XX:+UseG1GC -XX:G1ReservePercent=25 -XX:InitiatingHeapOccupancyPercent=30 -Djava.io.tmpdir=/tmp/elasticsearch-11517872886464217354 -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/var/lib/elasticsearch -XX:ErrorFile=/var/log/elasticsearch/hs_err_pid%p.log -Xlog:gc*,gc+age=trace,safepoint:file=/var/log/elasticsearch/gc.log:utctime,pid,tags:filecount=32,filesize=64m -Dclk.tck=100 -Djdk.attach.allowAttachSelf=true -Djava.security.policy=file:///usr/share/elasticsearch/plugins/opendistro-performance-analyzer/pa_config/es_security.policy -XX:MaxDirectMemorySize=536870912 -Des.path.home=/usr/share/elasticsearch -Des.path.conf=/etc/elasticsearch -Des.distribution.flavor=oss -Des.distribution.type=rpm -Des.bundled_jdk=true -cp /usr/share/elasticsearch/lib/* org.elasticsearch.bootstrap.Elasticsearch -p /var/run/elasticsearch/elasticsearch.pid --quiet
elastic+  5341 22.3  3.1 2426212 122168 ?      Sl   04:58   0:02 /usr/share/elasticsearch/jdk/bin/java -Xshare:auto -Xms4m -Xmx64m -XX:+UseSerialGC -Dlog4j.configurationFile=/usr/share/elasticsearch/plugins/opendistro-performance-analyzer/pa_config/log4j2.xml -Xms64M -Xmx64M -XX:+UseSerialGC -XX:CICompilerCount=1 -XX:-TieredCompilation -XX:InitialCodeCacheSize=4096 -XX:InitialBootClassLoaderMetaspaceSize=30720 -XX:MaxRAM=400m -Des.path.home=/usr/share/elasticsearch -Des.path.conf=/etc/elasticsearch -Des.distribution.flavor=oss -Des.distribution.type=rpm -cp /usr/share/elasticsearch/lib/*:/usr/share/elasticsearch/performance-analyzer-rca/lib/* com.amazon.opendistro.elasticsearch.performanceanalyzer.PerformanceAnalyzerApp
root      5661  0.0  0.0  12528   976 pts/0    S+   04:59   0:00 grep --color=auto java
```

We run `systemctl stop` and right after it check running processes again. Performance analyzer is still up
```
[root@host3 vagrant]# systemctl stop elasticsearch.service ; ps aux | grep java
elastic+  5341 13.1  3.2 2430324 126444 ?      Sl   04:58   0:03 /usr/share/elasticsearch/jdk/bin/java -Xshare:auto -Xms4m -Xmx64m -XX:+UseSerialGC -Dlog4j.configurationFile=/usr/share/elasticsearch/plugins/opendistro-performance-analyzer/pa_config/log4j2.xml -Xms64M -Xmx64M -XX:+UseSerialGC -XX:CICompilerCount=1 -XX:-TieredCompilation -XX:InitialCodeCacheSize=4096 -XX:InitialBootClassLoaderMetaspaceSize=30720 -XX:MaxRAM=400m -Des.path.home=/usr/share/elasticsearch -Des.path.conf=/etc/elasticsearch -Des.distribution.flavor=oss -Des.distribution.type=rpm -cp /usr/share/elasticsearch/lib/*:/usr/share/elasticsearch/performance-analyzer-rca/lib/* com.amazon.opendistro.elasticsearch.performanceanalyzer.PerformanceAnalyzerApp
root      5687  0.0  0.0  12528   972 pts/0    S+   04:59   0:00 grep --color=auto java
```

Just a moment later check the processes again and they are both gone:
```
[root@host3 vagrant]# ps aux | grep java
root      5690  0.0  0.0  12528   976 pts/0    S+   04:59   0:00 grep --color=auto java
```

We can also fix this easily in the SPEC since we have a single spec for elasticsearch and all the plugins so we could stop the performance analyzer first. Other option I found was setting the order to the performance analyzer service to start after elasticsearch, and in that way it will be stopped before it. I need to check if this could have any negative impact. I opened an issue to performance analyzer for that: https://github.com/opendistro-for-elasticsearch/performance-analyzer/issues/310


Other problem I found was that the performance analyzer did not work after an upgrade. I could fix this in the SPEC, but anyway this also happens for elasticsearch, so I added more details to an existing issue: https://github.com/opendistro-for-elasticsearch/performance-analyzer/issues/281

**Comment by sbruno** [comment]
Note, besides the [main branch for the feature](https://github.com/wazuh/wazuh-packages/tree/679-wazuh-indexer), I also left a branch including the feature to install using `SUBSEQUENT_NODE=true` as environment variable to avoid installing the `/var/lib/wazuh-indexer/nodes` data: https://github.com/wazuh/wazuh-packages/compare/679-wazuh-indexer...679-wazuh-indexer-env-var

And also a branch containing wazuh-indexer 4.2.0 specs which contain 1.12.0 ODFE (which includes ES 7.10.0), instead of 1.13.1 (which uses ES 7.10.2) used in the 5.0.0 SPEC. This can be used for testing an upgrade. The SPECs are almost the same, except for the versions, some name changes in the plugins or replaced plugins. It will get the ODFE tgz from a different S3 location: https://github.com/wazuh/wazuh-packages/compare/679-wazuh-indexer...679-wazuh-indexer-upgrade-test-spec
