### ISSUE TITLE
wazuh-kibana-app plugin takes too long to build

### ISSUE THREAD

**Issue by thesrinivas** [wazuh/wazuh-packages#796]
To build the Wazuh-kibana-app plugin using the command,
./generate_wazuh_app.sh -b v4.1.5-7.10.2 -s /wazuh-app -r 1,
takes about an hour. This is too long to test some changes/updates on the Kibana UI.
Is there a way to optimize the build time?
https://documentation.wazuh.com/current/development/packaging/generate-wazuh-kibana-app.html

**Comment by rauldpm** [comment]
Hello @thesrinivas

Sorry for the late reply, in which part of the package construction are you having problems or taking the longest time?

The build of this package is done through a Docker container, so it will be limited by the specifications of the host machine, in my case, the package takes me 9 minutes to build. Currently docker has no hardware limitation in its execution so it will use everything that is available https://docs.docker.com/config/containers/resource_constraints/

So that you have a reference, my hardware is:

- i7-10750H @ 2.60GHz (6 cores and 12 threads)
- SSD 512 GB NVMe PCIe 3.0
- 16GB DDR4-3200

You can check the status of Docker execution using the "docker stats" command while the package is being built, this way you can identify if there is any possible bottleneck in your hardware and thus be able to improve it.

An option that you can try is to modify the script so that it uses a container with the necessary software, such as the content of the repositories, the necessary dependencies and in this way the generation script only had to execute yarn (which is where it takes the longest time in my case)

**Comment by alberpilot** [comment]
Due to inactivity, I process to close this issue. Please don't hesitate to open it again if needed.
