### ISSUE TITLE
Different behavior between Wazuh manager upgrading and Wazuh API upgrading

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-packages#81]
Hello team, when upgrading our Wazuh manager or the Wazuh API we have different behavior between them.

- If you upgrade the Wazuh API and it detects that the Wazuh manager version is lower, the Wazuh API enforces upgrading the Wazuh manager.
- If you install the Wazuh API and it detects that the Wazuh manager is missing, it installs the Wazuh manager by itself.

But there is a different use case:

- If you upgrade the Wazuh manager, it doesn't tell you that the Wazuh API is outdated (and __probably broken__) so from my view, I think we must do something similar. We can check if the Wazuh manager has the same major and minor but different patch in its version. Since the Wazuh API is compatible with the same __major + minor__ we don't need to check the patch number. But if the Wazuh manager detects a different __major__  or a different __minor__  in the Wazuh API, it should remove or upgrade it. 

This could break integrations with third-party software such as Kibana and a few other things.

Regards!

**Comment by BraulioV** [comment]
Hi @jesusgn90,

this behavior is caused by this line in rpm https://github.com/wazuh/wazuh-packages/blob/fc80831cb320177462e4bf79a00cb7d3690cc7cc/rpms/SPECS/3.7.0/wazuh-api-3.7.0.spec#L18 
and this line in deb https://github.com/wazuh/wazuh-packages/blob/fc80831cb320177462e4bf79a00cb7d3690cc7cc/debs/SPECS/3.7.0/wazuh-api/debian/control#L11

As you said, if you upgrade the Wazuh API, the manager will also be updated, but, this is not the case if you upgrade the manager.

The solution is to control force the compatibility between patches in the dependencies fields of the packages or forcing the Wazuh API to have the same version as the Wazuh manager. For now, I will create a branch that implements the second option.

Regards!!
