### ISSUE TITLE
Problem with elastic-stack-installation.sh

### ISSUE THREAD

**Issue by rick-vini** [wazuh/wazuh-packages#986]
Hello, 

I encountered a small problem with the [unattended-installation script](https://packages.wazuh.com/resources/4.2/open-distro/unattended-installation/distributed/elastic-stack-installation.sh) from the [documentation](https://documentation.wazuh.com/current/installation-guide/open-distro/distributed-deployment/unattended/unattended-elasticsearch-cluster-installation.html). When trying to run it on Debian 11 or Ubuntu 20.04 distributions I got the following two errors:
```
/root/elastic-stack-installation.sh: line 556: [: -lt: expected unary operator
/root/elastic-stack-installation.sh: line 302: / 2 : syntax error: expected operand (error token is "/2")
```
I found that to fix those problems it was only necessary to change the value "**Mem:**" by "**Mem.:**" in the script elastic-stack-installation.sh. It was just missing the **dot** after Mem in those cases.

Hope this helps.

**Comment by rauldpm** [comment]
Hello @rick-vini 

I have transferred this issue to the wazuh-packages repository since in principle it is a problem with the installer itself and not with documentation.

I can not reproduce the problem that you indicate in debian11 and ubuntu20 following the same steps in the documentation, lines 301 and 302 correspond to:

```
ram_gb=$(free -g | awk '/^Mem:/{print $2}')
ram=$(( ${ram_gb} / 2 ))
```

The `free -g` command in ubuntu20 and debian11 returns the value `Mem:` not `Mem.:`

![com2](https://user-images.githubusercontent.com/14913942/140957477-3502f2b8-4842-45c7-9e84-8552f97649a2.png)

![com1](https://user-images.githubusercontent.com/14913942/140957481-bd228aba-c5cb-4216-a137-a19976906a8b.png)

If we accept your change, we get precisely the error you mentioned, which occurs since `$(free -g | awk '/^Mem.:/{print $2}')` does not return any value as shown in the following image:

![imagen3](https://user-images.githubusercontent.com/14913942/140957529-d1d3cffa-5725-41a4-a525-d237d65845fa.png)

That said, have you modified the script in any way? You can execute the command `free -g` and `free -g | awk '/^Mem:/{print $2}'` directly in the terminal and show us the result? It is weird that the output offered by free changes.

Regarding the error of line 556:

`if [ ${cores} -lt 2 ] || [ ${ram_gb} -lt 3700 ]; then`

I have not been able to reproduce it either, even adding the dot you comment (you can see that it does not get memory value:

![cores](https://user-images.githubusercontent.com/14913942/140957679-170d5199-6dde-4033-b280-3bfea7265ff9.png)

At first it occurs to me that this may be due to the brackets, can you try to modify the script and use double brackets? 

`[[ $ {cores} -lt 20 ]] || [[ ... ]]`

Finally, to secure the system, can you run the following command to check the version of the systems you are commenting on to make sure there is no difference?

`cat /etc/os-release`

You should see something like this:

![system](https://user-images.githubusercontent.com/14913942/140957710-7ca94717-9b84-4c48-b88c-966586f05543.png)

**Comment by rick-vini** [comment]
Hello @rauldpm,

thanks for the feedback.

After seeing your answer, I verified that the problem is in the language used in the OS. When I use pt_BR the free command returns "Mem.:" :

![br](https://user-images.githubusercontent.com/5281277/141044227-286484bc-5250-4273-a5c9-231588d03262.png)

When the language is en_US the free command returns "Mem:" :

![us](https://user-images.githubusercontent.com/5281277/141044420-120141cc-bbf3-4383-aa37-1af81058aa16.png)

I've corrected the language and everything worked out in a new test. Thank you for your attention.

Regards, Ricardo.

**Comment by rauldpm** [comment]
Hello @rick-vini 

It is true that it is a situation that is not controlled but because there is a large amount of possibilities in terms of language. Thank you for notifying us, we will try to find some generic way that allows us to obtain this.

Anyway, from what I see in the image, the `free -g` command still shows `Mem.:` while using `en_US` locale. If you have managed to fix it, great, but as I said, we will investigate how to obtain these values in the best generic way possible.

Regards, Raúl.

**Comment by rick-vini** [comment]
Hi @rauldpm

Sorry, I upload the wrong image file. That one was before de reboot. This is the correct one for the en_US:

![us](https://user-images.githubusercontent.com/5281277/141410772-4302b168-2f07-4106-857e-0d9c0f3e40ba.png)

Anyway, I've corrected the language and everything worked out in a new test. Thank you for your attention.

Regards, Ricardo.
